server:
  port: 8888

spring:
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:kudaatwork}
      password: ${CONFIG_SERVER_PASSWORD:changeme
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: ${LDMS_CONFIG_GIT_URI}
          clone-on-start: true
          default-label: ${LDMS_CONFIG_GIT_BRANCH:main}
          search-paths: '{profile}'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized