package projectlx.fuel.expenses.utils.enums;

public enum FuelTelemetrySource {

    /** Reading submitted by the driver via the mobile app. */
    DRIVER_APP,

    /** Reading received from an on-board telematics device. */
    TELEMATICS,

    /** Synthetic reading generated by the IoT demo simulator. */
    SIMULATED,

    /** Reading entered manually by an operator. */
    MANUAL,

    /** Reading computed by the platform system (e.g. consumption delta from location update). */
    SYSTEM
}
