server:
  port: 8093

spring:
  application:
    name: ldms-billing-payments
  datasource:
    url: jdbc:mysql://localhost:3306/ldms_billing_payments?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    show-sql: true

management:
  server:
    port: 9093
