server:
  port: 8084

spring:
  application:
    name: ldms-location-management
  datasource:
    url: jdbc:mysql://localhost:3306/ldms_location_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

management:
  server:
    port: 9084
