server:
  port: 8088

spring:
  application:
    name: ldms-documents-management
  datasource:
    url: jdbc:mysql://localhost:3306/ldms_documents_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

management:
  server:
    port: 9088

ldms:
  file-service:
    base-url: http://localhost:8200
    internal-token: ${FILE_SERVICE_TOKEN}
    max-file-size-mb: 50
