server:
  port: 8089

spring:
  application:
    name: ldms-fleet-management
  datasource:
    url: jdbc:mysql://localhost:3306/ldms_fleet_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

management:
  server:
    port: 9089

clients:
  base-url:
    documents-management: http://ldms-documents-management
    user-management: http://ldms-user-management

ldms:
  fleet:
    compliance-warning-days: 30
