server:
  port: 8010

application:
  name: ldms-shared-library
  description: LDMS Shared Library Management System

jwt:
  secret: N2V3XSEJkdZ2aHf4xCOHAZHWbDhgFjnBjdfFaeJze0yJiWvSLlhnIxRpkDsr17ZsUCAL2soOEKF9iGXELjs1Kw==
  access-token-expiration-ms: 900000    # 15 minutes
  refresh-token-expiration-ms: 604800000 # 7 days