package projectlx.trip.tracking.utils.enums;

public enum TripEventType {
    DEPARTED,
    ARRIVED_AT_BORDER,
    BORDER_CLEARED,
    CHECKPOINT,
    ROADSIDE_FUEL_STOP,
    ROADSIDE_MECHANIC_STOP,
    ROADSIDE_RESUMED,
    DRIVER_BREAK,
    DRIVER_RESUMED,
    ARRIVED,
    STOCK_COUNTING_STARTED,
    STOCK_COUNTING_FINISHED,
    OTP_SENT,
    OTP_VERIFIED,
    DELIVERED,
    RETURN_INITIATED,
    RETURN_RECORDED,
    RETURN_CONFIRMED,
    NOTE
}
