package projectlx.inventory.management.utils.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum I18Code {

    MESSAGE_ID_SUPPLIED_INVALID("message.id.supplied.invalid"),
    MESSAGE_STRING_SUPPLIED_IS_NULL("message.string.supplied.is.null"),
    // Generic validation messages (cross-cutting)
    MESSAGE_PRODUCT_ID_REQUIRED("message.product.id.required"),
    MESSAGE_WAREHOUSE_LOCATION_ID_REQUIRED("message.warehouse.location.id.required"),
    MESSAGE_SUPPLIER_ID_REQUIRED("message.supplier.id.required"),
    MESSAGE_QUANTITY_MUST_BE_POSITIVE("message.quantity.must.be.positive"),
    MESSAGE_UNIT_COST_MUST_BE_NON_NEGATIVE("message.unit.cost.must.be.non.negative"),
    MESSAGE_MIN_STOCK_LEVEL_MUST_BE_NON_NEGATIVE("message.min.stock.level.must.be.non.negative"),
    MESSAGE_REORDER_QUANTITY_MUST_BE_NON_NEGATIVE("message.reorder.quantity.must.be.non.negative"),
    MESSAGE_USER_ID_REQUIRED("message.user.id.required"),

    // Initial Stock messages
    MESSAGE_CREATE_INITIAL_STOCK_INVALID_REQUEST("message.create.initial.stock.invalid.request"),
    MESSAGE_INITIAL_STOCK_ALREADY_EXISTS("message.initial.stock.already.exists"),
    MESSAGE_INITIAL_STOCK_CREATED_SUCCESSFULLY("message.initial.stock.created.successfully"),

    // Product messages
    MESSAGE_PRODUCT_NOT_FOUND("message.product.not.found"),
    MESSAGE_PRODUCT_ALREADY_EXISTS("message.product.already.exists"),
    MESSAGE_CREATE_PRODUCT_INVALID_REQUEST("message.create.product.invalid.request"),
    MESSAGE_CREATE_PRODUCT_REQUEST_IS_NULL("message.create.product.request.is.null"),
    MESSAGE_CREATE_PRODUCT_NAME_MISSING("message.create.product.name.missing"),
    MESSAGE_CREATE_PRODUCT_CODE_MISSING("message.create.product.code.missing"),
    MESSAGE_CREATE_PRODUCT_PRICE_INVALID("message.create.product.price.invalid"),
    MESSAGE_CREATE_PRODUCT_UNIT_OF_MEASURE_MISSING("message.create.product.unit.of.measure.missing"),
    MESSAGE_CREATE_PRODUCT_CATEGORY_ID_INVALID("message.create.product.category.id.invalid"),
    MESSAGE_CREATE_PRODUCT_SUPPLIER_ID_INVALID("message.create.product.supplier.id.invalid"),
    MESSAGE_CREATE_PRODUCT_INVALID_IMAGE_UPLOAD("message.create.product.invalid.image.upload"),
    MESSAGE_PRODUCT_CREATED_SUCCESSFULLY("message.product.created.successfully"),
    MESSAGE_PRODUCT_RETRIEVED_SUCCESSFULLY("message.product.retrieved.successfully"),
    MESSAGE_UPDATE_PRODUCT_INVALID_REQUEST("message.update.product.invalid.request"),
    MESSAGE_UPDATE_PRODUCT_REQUEST_IS_NULL("message.update.product.request.is.null"),
    MESSAGE_UPDATE_PRODUCT_ID_INVALID("message.update.product.id.invalid"),
    MESSAGE_UPDATE_PRODUCT_CATEGORY_ID_INVALID("message.update.product.category.id.invalid"),
    MESSAGE_UPDATE_PRODUCT_SUPPLIER_ID_INVALID("message.update.product.supplier.id.invalid"),
    MESSAGE_UPDATE_PRODUCT_PRICE_INVALID("message.update.product.price.invalid"),
    MESSAGE_UPDATE_PRODUCT_INVALID_IMAGE_UPLOAD("message.update.product.invalid.image.upload"),
    MESSAGE_PRODUCT_UPDATED_SUCCESSFULLY("message.product.updated.successfully"),
    MESSAGE_PRODUCT_DELETED_SUCCESSFULLY("message.product.deleted.successfully"),
    // Product multiple filters
    MESSAGE_PRODUCT_INVALID_MULTIPLE_FILTERS_REQUEST("message.product.invalid.multiple.filters.request"),
    MESSAGE_PRODUCT_REQUEST_IS_NULL("message.product.request.is.null"),
    MESSAGE_PRODUCT_PAGE_NEGATIVE("message.product.page.negative"),
    MESSAGE_PRODUCT_SIZE_INVALID("message.product.size.invalid"),
    MESSAGE_PRODUCT_PAGE_OUT_OF_BOUNDS("message.product.page.out.of.bounds"),

    // Product Category messages
    MESSAGE_PRODUCT_CATEGORY_NOT_FOUND("message.product.category.not.found"),
    MESSAGE_PRODUCT_CATEGORY_ALREADY_EXISTS("message.product.category.already.exists"),
    MESSAGE_CREATE_PRODUCT_CATEGORY_INVALID_REQUEST("message.create.product.category.invalid.request"),
    MESSAGE_CREATE_PRODUCT_CATEGORY_REQUEST_IS_NULL("message.create.product.category.request.is.null"),
    MESSAGE_CREATE_PRODUCT_CATEGORY_NAME_MISSING("message.create.product.category.name.missing"),
    MESSAGE_CREATE_PRODUCT_CATEGORY_DESCRIPTION_MISSING("message.create.product.category.description.missing"),
    MESSAGE_PRODUCT_CATEGORY_CREATED_SUCCESSFULLY("message.product.category.created.successfully"),
    MESSAGE_PRODUCT_CATEGORY_RETRIEVED_SUCCESSFULLY("message.product.category.retrieved.successfully"),
    MESSAGE_UPDATE_PRODUCT_CATEGORY_INVALID_REQUEST("message.update.product.category.invalid.request"),
    MESSAGE_UPDATE_PRODUCT_CATEGORY_REQUEST_IS_NULL("message.update.product.category.request.is.null"),
    MESSAGE_UPDATE_PRODUCT_CATEGORY_NAME_MISSING("message.update.product.category.name.missing"),
    MESSAGE_UPDATE_PRODUCT_CATEGORY_DESCRIPTION_MISSING("message.update.product.category.description.missing"),
    MESSAGE_PRODUCT_CATEGORY_UPDATED_SUCCESSFULLY("message.product.category.updated.successfully"),
    MESSAGE_PRODUCT_CATEGORY_DELETED_SUCCESSFULLY("message.product.category.deleted.successfully"),

    // Multiple filters validations for categories
    MESSAGE_PRODUCT_CATEGORY_INVALID_MULTIPLE_FILTERS_REQUEST("message.product.category.invalid.multiple.filters.request"),
    MESSAGE_PRODUCT_CATEGORY_REQUEST_IS_NULL("message.product.category.request.is.null"),
    MESSAGE_PRODUCT_CATEGORY_PAGE_NEGATIVE("message.product.category.page.negative"),
    MESSAGE_PRODUCT_CATEGORY_SIZE_INVALID("message.product.category.size.invalid"),
    MESSAGE_PRODUCT_CATEGORY_PAGE_OUT_OF_BOUNDS("message.product.category.page.out.of.bounds"),

    // Product SubCategory messages
    MESSAGE_PRODUCT_SUB_CATEGORY_NOT_FOUND("message.product.sub.category.not.found"),
    MESSAGE_PRODUCT_SUB_CATEGORY_ALREADY_EXISTS("message.product.sub.category.already.exists"),
    MESSAGE_CREATE_PRODUCT_SUB_CATEGORY_INVALID_REQUEST("message.create.product.sub.category.invalid.request"),
    MESSAGE_CREATE_PRODUCT_SUB_CATEGORY_REQUEST_IS_NULL("message.create.product.sub.category.request.is.null"),
    MESSAGE_CREATE_PRODUCT_SUB_CATEGORY_CATEGORY_ID_INVALID("message.create.product.sub.category.category.id.invalid"),
    MESSAGE_CREATE_PRODUCT_SUB_CATEGORY_NAME_MISSING("message.create.product.sub.category.name.missing"),
    MESSAGE_CREATE_PRODUCT_SUB_CATEGORY_DESCRIPTION_MISSING("message.create.product.sub.category.description.missing"),
    MESSAGE_CREATE_PRODUCT_SUB_CATEGORY_CATEGORY_NOT_FOUND("message.create.product.sub.category.category.not.found"),
    MESSAGE_PRODUCT_SUB_CATEGORY_CREATED_SUCCESSFULLY("message.product.sub.category.created.successfully"),
    MESSAGE_PRODUCT_SUB_CATEGORY_RETRIEVED_SUCCESSFULLY("message.product.sub.category.retrieved.successfully"),
    MESSAGE_UPDATE_PRODUCT_SUB_CATEGORY_INVALID_REQUEST("message.update.product.sub.category.invalid.request"),
    MESSAGE_UPDATE_PRODUCT_SUB_CATEGORY_REQUEST_IS_NULL("message.update.product.sub.category.request.is.null"),
    MESSAGE_UPDATE_PRODUCT_SUB_CATEGORY_ID_INVALID("message.update.product.sub.category.id.invalid"),
    MESSAGE_UPDATE_PRODUCT_SUB_CATEGORY_CATEGORY_ID_INVALID("message.update.product.sub.category.category.id.invalid"),
    MESSAGE_UPDATE_PRODUCT_SUB_CATEGORY_NAME_MISSING("message.update.product.sub.category.name.missing"),
    MESSAGE_UPDATE_PRODUCT_SUB_CATEGORY_DESCRIPTION_MISSING("message.update.product.sub.category.description.missing"),
    MESSAGE_PRODUCT_SUB_CATEGORY_UPDATED_SUCCESSFULLY("message.product.sub.category.updated.successfully"),
    MESSAGE_PRODUCT_SUB_CATEGORY_DELETED_SUCCESSFULLY("message.product.sub.category.deleted.successfully"),

    // Multiple filters validations for subcategories
    MESSAGE_PRODUCT_SUB_CATEGORY_INVALID_MULTIPLE_FILTERS_REQUEST("message.product.sub.category.invalid.multiple.filters.request"),
    MESSAGE_PRODUCT_SUB_CATEGORY_REQUEST_IS_NULL("message.product.sub.category.request.is.null"),
    MESSAGE_PRODUCT_SUB_CATEGORY_PAGE_OUT_OF_BOUNDS("message.product.sub.category.page.out.of.bounds"),

    // Warehouse Location messages
    MESSAGE_WAREHOUSE_LOCATION_NOT_FOUND("message.warehouse.location.not.found"),
    MESSAGE_CREATE_WAREHOUSE_LOCATION_INVALID_REQUEST("message.create.warehouse.location.invalid.request"),
    MESSAGE_CREATE_WAREHOUSE_LOCATION_REQUEST_IS_NULL("message.create.warehouse.location.request.is.null"),
    MESSAGE_CREATE_WAREHOUSE_LOCATION_LINE1_MISSING("message.create.warehouse.location.line1.missing"),
    MESSAGE_CREATE_WAREHOUSE_LOCATION_NAME_MISSING("message.create.warehouse.location.name.missing"),
    MESSAGE_CREATE_WAREHOUSE_LOCATION_DESCRIPTION_MISSING("message.create.warehouse.location.description.missing"),
    MESSAGE_WAREHOUSE_LOCATION_CREATED_SUCCESSFULLY("message.warehouse.location.created.successfully"),
    MESSAGE_WAREHOUSE_LOCATION_RETRIEVED_SUCCESSFULLY("message.warehouse.location.retrieved.successfully"),
    MESSAGE_UPDATE_WAREHOUSE_LOCATION_INVALID_REQUEST("message.update.warehouse.location.invalid.request"),
    MESSAGE_UPDATE_WAREHOUSE_LOCATION_REQUEST_IS_NULL("message.update.warehouse.location.request.is.null"),
    MESSAGE_UPDATE_WAREHOUSE_LOCATION_ID_INVALID("message.update.warehouse.location.id.invalid"),
    MESSAGE_UPDATE_WAREHOUSE_LOCATION_NAME_MISSING("message.update.warehouse.location.name.missing"),
    MESSAGE_UPDATE_WAREHOUSE_LOCATION_DESCRIPTION_MISSING("message.update.warehouse.location.description.missing"),
    MESSAGE_WAREHOUSE_LOCATION_UPDATED_SUCCESSFULLY("message.warehouse.location.updated.successfully"),
    MESSAGE_WAREHOUSE_LOCATION_DELETED_SUCCESSFULLY("message.warehouse.location.deleted.successfully"),

    // Multiple filters validations for warehouse locations
    MESSAGE_WAREHOUSE_LOCATION_INVALID_MULTIPLE_FILTERS_REQUEST("message.warehouse.location.invalid.multiple.filters.request"),
    MESSAGE_WAREHOUSE_LOCATION_REQUEST_IS_NULL("message.warehouse.location.request.is.null"),
    MESSAGE_WAREHOUSE_LOCATION_PAGE_NEGATIVE("message.warehouse.location.page.negative"),
    MESSAGE_WAREHOUSE_LOCATION_SIZE_INVALID("message.warehouse.location.size.invalid"),
    MESSAGE_WAREHOUSE_LOCATION_PAGE_OUT_OF_BOUNDS("message.warehouse.location.page.out.of.bounds"),

    // Product Document messages
    MESSAGE_PRODUCT_DOCUMENT_NOT_FOUND("message.product.document.not.found"),
    MESSAGE_CREATE_PRODUCT_DOCUMENT_INVALID_REQUEST("message.create.product.document.invalid.request"),
    MESSAGE_CREATE_PRODUCT_DOCUMENT_REQUEST_IS_NULL("message.create.product.document.request.is.null"),
    MESSAGE_CREATE_PRODUCT_DOCUMENT_PRODUCT_ID_INVALID("message.create.product.document.product.id.invalid"),
    MESSAGE_CREATE_PRODUCT_DOCUMENT_NAME_MISSING("message.create.product.document.name.missing"),
    // Note: upload may be optional to allow CSV imports
    MESSAGE_CREATE_PRODUCT_DOCUMENT_UPLOAD_MISSING("message.create.product.document.upload.missing"),
    MESSAGE_PRODUCT_DOCUMENT_CREATED_SUCCESSFULLY("message.product.document.created.successfully"),
    MESSAGE_PRODUCT_DOCUMENT_RETRIEVED_SUCCESSFULLY("message.product.document.retrieved.successfully"),
    MESSAGE_UPDATE_PRODUCT_DOCUMENT_INVALID_REQUEST("message.update.product.document.invalid.request"),
    MESSAGE_PRODUCT_DOCUMENT_UPDATED_SUCCESSFULLY("message.product.document.updated.successfully"),
    MESSAGE_PRODUCT_DOCUMENT_DELETED_SUCCESSFULLY("message.product.document.deleted.successfully"),
    // Multiple filters validations for product documents
    MESSAGE_PRODUCT_DOCUMENT_INVALID_MULTIPLE_FILTERS_REQUEST("message.product.document.invalid.multiple.filters.request"),
    MESSAGE_PRODUCT_DOCUMENT_REQUEST_IS_NULL("message.product.document.request.is.null"),
    MESSAGE_PRODUCT_DOCUMENT_PAGE_NEGATIVE("message.product.document.page.negative"),
    MESSAGE_PRODUCT_DOCUMENT_SIZE_INVALID("message.product.document.size.invalid"),
    MESSAGE_PRODUCT_DOCUMENT_PAGE_OUT_OF_BOUNDS("message.product.document.page.out.of.bounds"),

    // Purchase Order messages
    MESSAGE_PURCHASE_ORDER_NOT_FOUND("message.purchase.order.not.found"),
    MESSAGE_CREATE_PURCHASE_ORDER_INVALID_REQUEST("message.create.purchase.order.invalid.request"),
    MESSAGE_CREATE_PURCHASE_ORDER_REQUEST_IS_NULL("message.create.purchase.order.request.is.null"),
    MESSAGE_CREATE_PURCHASE_ORDER_SUPPLIER_ID_REQUIRED("message.create.purchase.order.supplier.id.required"),
    MESSAGE_CREATE_PURCHASE_ORDER_SHIP_FROM_LOCATION_ID_REQUIRED("message.create.purchase.order.ship.from.location.id.required"),
    MESSAGE_CREATE_PURCHASE_ORDER_SHIP_TO_LOCATION_ID_REQUIRED("message.create.purchase.order.ship.to.location.id.required"),
    MESSAGE_CREATE_PURCHASE_ORDER_RECEIVING_WAREHOUSE_ID_REQUIRED("message.create.purchase.order.receiving.warehouse.id.required"),
    MESSAGE_CREATE_PURCHASE_ORDER_LINE_PRODUCT_ID_REQUIRED("message.create.purchase.order.line.product.id.required"),
    MESSAGE_CREATE_PURCHASE_ORDER_LINE_PRODUCT_NOT_FOUND_OR_DELETED("message.create.purchase.order.line.product.not.found.or.deleted"),
    MESSAGE_CREATE_PURCHASE_ORDER_LINE_UNIT_OF_MEASURE_REQUIRED("message.create.purchase.order.line.unit.of.measure.required"),
    MESSAGE_CREATE_PURCHASE_ORDER_LINE_QUANTITY_REQUIRED("message.create.purchase.order.line.quantity.required"),
    MESSAGE_CREATE_PURCHASE_ORDER_LINE_UNIT_PRICE_REQUIRED("message.create.purchase.order.line.unit.price.required"),
    MESSAGE_PURCHASE_ORDER_SHIP_FROM_LOCATION_INVALID_TYPE("message.purchase.order.ship.from.location.invalid.type"),
    MESSAGE_PURCHASE_ORDER_SHIP_TO_LOCATION_INVALID_TYPE("message.purchase.order.ship.to.location.invalid.type"),
    MESSAGE_PURCHASE_ORDER_RECEIVING_WAREHOUSE_INVALID_TYPE("message.purchase.order.receiving.warehouse.invalid.type"),
    MESSAGE_PURCHASE_ORDER_CREATED_SUCCESSFULLY("message.purchase.order.created.successfully"),
    MESSAGE_PURCHASE_ORDER_RETRIEVED_SUCCESSFULLY("message.purchase.order.retrieved.successfully"),
    MESSAGE_UPDATE_PURCHASE_ORDER_REQUEST_IS_NULL("message.update.purchase.order.request.is.null"),
    MESSAGE_INVALID_STATUS_TRANSITION("message.invalid.status.transition"),
    MESSAGE_EDIT_PURCHASE_ORDER_REQUEST_IS_NULL("message.edit.purchase.order.request.is.null"),
    MESSAGE_EDIT_PURCHASE_ORDER_ID_REQUIRED("message.edit.purchase.order.id.required"),
    MESSAGE_APPROVE_PURCHASE_ORDER_SUPPLIER_ID_REQUIRED("message.approve.purchase.order.supplier.id.required"),
    MESSAGE_APPROVE_PURCHASE_ORDER_ORDER_DATE_REQUIRED("message.approve.purchase.order.order.date.required"),
    MESSAGE_PURCHASE_ORDER_UPDATED_SUCCESSFULLY("message.purchase.order.updated.successfully"),
    MESSAGE_PURCHASE_ORDER_DELETED_SUCCESSFULLY("message.purchase.order.deleted.successfully"),
    MESSAGE_PURCHASE_ORDER_NOT_EDITABLE("message.purchase.order.not.editable"),

    // Receive Goods messages
    MESSAGE_RECEIVE_GOODS_INVALID_REQUEST("message.receive.goods.invalid.request"),
    MESSAGE_RECEIVE_GOODS_REQUEST_IS_NULL_OR_MISSING_REQUIRED_FIELDS("message.receive.goods.request.is.null.or.missing.required.fields"),
    MESSAGE_RECEIVE_GOODS_PURCHASE_ORDER_NOT_RECEIVABLE("message.receive.goods.po.not.receivable"),
    MESSAGE_RECEIVE_GOODS_SUCCESSFUL("message.receive.goods.successful"),
    MESSAGE_RECEIVE_GOODS_PARTIALLY_RECEIVED("message.receive.goods.partially.received"),
    MESSAGE_RECEIVE_GOODS_FAILED("message.receive.goods.failed"),

    //Purchase Order Line messages
    MESSAGE_CREATE_PURCHASE_ORDER_LINE_INVALID_REQUEST("message.create.purchase.order.line.invalid.request"),
    MESSAGE_PURCHASE_ORDER_LINE_CREATED_SUCCESSFULLY("message.purchase.order.line.created.successfully"),
    MESSAGE_PURCHASE_ORDER_LINE_NOT_FOUND("message.purchase.order.line.not.found"),
    MESSAGE_PURCHASE_ORDER_LINE_RETRIEVED_SUCCESSFULLY("message.purchase.order.line.retrieved.successfully"),
    MESSAGE_UPDATE_PURCHASE_ORDER_LINE_INVALID_REQUEST("message.update.purchase.order.line.invalid.request"),
    MESSAGE_PURCHASE_ORDER_LINE_UPDATED_SUCCESSFULLY("message.purchase.order.line.updated.successfully"),
    MESSAGE_PURCHASE_ORDER_LINE_DELETED_SUCCESSFULLY("message.purchase.order.line.deleted.successfully"),
    MESSAGE_PURCHASE_ORDER_LINE_INVALID_MULTIPLE_FILTERS_REQUEST("message.purchase.order.line.invalid.multiple.filters.request"),
    MESSAGE_PURCHASE_ORDER_LINE_PAGE_OUT_OF_BOUNDS("message.purchase.order.line.page.out.of.bounds"),

    // Inventory Items messages
    MESSAGE_INVENTORY_ITEM_NOT_FOUND("message.inventory.item.not.found"),
    MESSAGE_INVENTORY_ITEM_ALREADY_EXISTS_FOR_LOCATION("message.inventory.item.already.exists.for.location"),
    MESSAGE_CREATE_INVENTORY_ITEM_INVALID_REQUEST("message.create.inventory.item.invalid.request"),
    MESSAGE_CREATE_INVENTORY_ITEM_REQUEST_IS_NULL("message.create.inventory.item.request.is.null"),
    MESSAGE_CREATE_INVENTORY_ITEM_PRODUCT_ID_INVALID("message.create.inventory.item.product.id.invalid"),
    MESSAGE_CREATE_INVENTORY_ITEM_WAREHOUSE_LOCATION_ID_INVALID("message.create.inventory.item.warehouse.location.id.invalid"),
    MESSAGE_CREATE_INVENTORY_ITEM_CURRENT_STOCK_INVALID("message.create.inventory.item.current.stock.invalid"),
    MESSAGE_INVENTORY_ITEM_CREATED_SUCCESSFULLY("message.inventory.item.created.successfully"),
    MESSAGE_INVENTORY_ITEM_RETRIEVED_SUCCESSFULLY("message.inventory.item.retrieved.successfully"),
    MESSAGE_UPDATE_INVENTORY_ITEM_INVALID_REQUEST("message.update.inventory.item.invalid.request"),
    MESSAGE_EDIT_INVENTORY_ITEM_REQUEST_IS_NULL("message.edit.inventory.item.request.is.null"),
    MESSAGE_EDIT_INVENTORY_ITEM_ID_INVALID("message.edit.inventory.item.id.invalid"),
    MESSAGE_INVENTORY_ITEM_UPDATED_SUCCESSFULLY("message.inventory.item.updated.successfully"),
    MESSAGE_INVENTORY_ITEM_DELETED_SUCCESSFULLY("message.inventory.item.deleted.successfully"),
    MESSAGE_INVENTORY_ITEM_INSUFFICIENT_STOCK("message.inventory.item.insufficient.stock"),
    MESSAGE_INVENTORY_UPDATE_FAILED("message.inventory.update.failed"),
    
    // Multiple filters validations for inventory items
    MESSAGE_INVENTORY_ITEM_INVALID_MULTIPLE_FILTERS_REQUEST("message.inventory.item.invalid.multiple.filters.request"),
    MESSAGE_INVENTORY_ITEM_REQUEST_IS_NULL("message.inventory.item.request.is.null"),
    MESSAGE_INVENTORY_ITEM_PAGE_NEGATIVE("message.inventory.item.page.negative"),
    MESSAGE_INVENTORY_ITEM_SIZE_INVALID("message.inventory.item.size.invalid"),
    MESSAGE_INVENTORY_ITEM_PAGE_OUT_OF_BOUNDS("message.inventory.item.page.out.of.bounds"),

    // Stock Transaction History messages
    MESSAGE_CREATE_STOCK_TRANSACTION_HISTORY_INVALID_REQUEST("message.create.stock.transaction.history.invalid.request"),
    MESSAGE_CREATE_STOCK_TRANSACTION_HISTORY_REQUEST_IS_NULL("message.create.stock.transaction.history.request.is.null"),
    MESSAGE_CREATE_STOCK_TRANSACTION_HISTORY_INVENTORY_ITEM_ID_INVALID("message.create.stock.transaction.history.inventory.item.id.invalid"),
    MESSAGE_CREATE_STOCK_TRANSACTION_HISTORY_WAREHOUSE_LOCATION_ID_INVALID("message.create.stock.transaction.history.warehouse.location.id.invalid"),
    MESSAGE_CREATE_STOCK_TRANSACTION_HISTORY_PERFORMED_BY_USER_ID_INVALID("message.create.stock.transaction.history.performed.by.user.id.invalid"),
    MESSAGE_CREATE_STOCK_TRANSACTION_HISTORY_TRANSACTION_TYPE_MISSING("message.create.stock.transaction.history.transaction.type.missing"),
    MESSAGE_CREATE_STOCK_TRANSACTION_HISTORY_QUANTITY_CHANGE_INVALID("message.create.stock.transaction.history.quantity.change.invalid"),
    MESSAGE_CREATE_STOCK_TRANSACTION_HISTORY_REASON_MISSING("message.create.stock.transaction.history.reason.missing"),
    MESSAGE_UPDATE_STOCK_TRANSACTION_HISTORY_INVALID_REQUEST("message.update.stock.transaction.history.invalid.request"),
    MESSAGE_UPDATE_STOCK_TRANSACTION_HISTORY_REQUEST_IS_NULL("message.update.stock.transaction.history.request.is.null"),
    MESSAGE_UPDATE_STOCK_TRANSACTION_HISTORY_ID_INVALID("message.update.stock.transaction.history.id.invalid"),
    MESSAGE_UPDATE_STOCK_TRANSACTION_HISTORY_UPDATED_BY_USER_ID_INVALID("message.update.stock.transaction.history.updated.by.user.id.invalid"),
    MESSAGE_STOCK_TRANSACTION_HISTORY_NOT_FOUND("message.stock.transaction.history.not.found"),
    MESSAGE_STOCK_TRANSACTION_HISTORY_CREATED_SUCCESSFULLY("message.stock.transaction.history.created.successfully"),
    MESSAGE_STOCK_TRANSACTION_HISTORY_RETRIEVED_SUCCESSFULLY("message.stock.transaction.history.retrieved.successfully"),
    MESSAGE_STOCK_TRANSACTION_HISTORY_UPDATED_SUCCESSFULLY("message.stock.transaction.history.updated.successfully"),
    MESSAGE_STOCK_TRANSACTION_HISTORY_DELETED_SUCCESSFULLY("message.stock.transaction.history.deleted.successfully"),

    // Purchase Return messages
    MESSAGE_PURCHASE_RETURN_NOT_FOUND("message.purchase.return.not.found"),
    MESSAGE_CREATE_PURCHASE_RETURN_INVALID_REQUEST("message.create.purchase.return.invalid.request"),
    MESSAGE_CREATE_PURCHASE_RETURN_REQUEST_IS_NULL("message.create.purchase.return.request.is.null"),
    MESSAGE_CREATE_PURCHASE_RETURN_PURCHASE_ORDER_ID_INVALID("message.create.purchase.return.purchase.order.id.invalid"),
    MESSAGE_CREATE_PURCHASE_RETURN_WAREHOUSE_LOCATION_ID_INVALID("message.create.purchase.return.warehouse.location.id.invalid"),
    MESSAGE_CREATE_PURCHASE_RETURN_RETURNED_BY_USER_ID_INVALID("message.create.purchase.return.returned.by.user.id.invalid"),
    MESSAGE_CREATE_PURCHASE_RETURN_REASON_MISSING("message.create.purchase.return.reason.missing"),
    MESSAGE_CREATE_PURCHASE_RETURN_LINE_ITEMS_MISSING("message.create.purchase.return.line.items.missing"),
    MESSAGE_CREATE_PURCHASE_RETURN_LINE_PRODUCT_ID_INVALID("message.create.purchase.return.line.product.id.invalid"),
    MESSAGE_CREATE_PURCHASE_RETURN_LINE_QUANTITY_INVALID("message.create.purchase.return.line.quantity.invalid"),
    MESSAGE_CREATE_PURCHASE_RETURN_LINE_UNIT_COST_INVALID("message.create.purchase.return.line.unit.cost.invalid"),
    MESSAGE_PURCHASE_RETURN_CREATED_SUCCESSFULLY("message.purchase.return.created.successfully"),
    MESSAGE_PURCHASE_RETURN_RETRIEVED_SUCCESSFULLY("message.purchase.return.retrieved.successfully"),
    MESSAGE_EDIT_PURCHASE_RETURN_REQUEST_IS_NULL("message.edit.purchase.return.request.is.null"),
    MESSAGE_EDIT_PURCHASE_RETURN_ID_INVALID("message.edit.purchase.return.id.invalid"),
    MESSAGE_PURCHASE_RETURN_UPDATED_SUCCESSFULLY("message.purchase.return.updated.successfully"),
    MESSAGE_PURCHASE_RETURN_DELETED_SUCCESSFULLY("message.purchase.return.deleted.successfully"),
    
    // Purchase Return multiple filters
    MESSAGE_PURCHASE_RETURN_INVALID_MULTIPLE_FILTERS_REQUEST("message.purchase.return.invalid.multiple.filters.request"),
    MESSAGE_PURCHASE_RETURN_REQUEST_IS_NULL("message.purchase.return.request.is.null"),
    MESSAGE_PURCHASE_RETURN_PAGE_NEGATIVE("message.purchase.return.page.negative"),
    MESSAGE_PURCHASE_RETURN_SIZE_INVALID("message.purchase.return.size.invalid"),
    MESSAGE_PURCHASE_RETURN_PAGE_OUT_OF_BOUNDS("message.purchase.return.page.out.of.bounds"),
    
    // Purchase Return additional messages
    MESSAGE_PURCHASE_RETURN_PARTIALLY_RECORDED("message.purchase.return.partially.recorded"),
    MESSAGE_UPDATE_PURCHASE_RETURN_INVALID("message.update.purchase.return.invalid"),
    MESSAGE_PURCHASE_RETURN_INVENTORY_ITEM_NOT_FOUND("message.purchase.return.inventory.item.not.found"),
    MESSAGE_PURCHASE_RETURN_FAILED_TO_RECORD("message.purchase.return.failed.to.record"),
    MESSAGE_PURCHASE_RETURN_UNEXPECTED_ERROR("message.purchase.return.unexpected.error"),
    MESSAGE_PURCHASE_RETURN_IMPORT_ROW_ERROR("message.purchase.return.import.row.error"),
    MESSAGE_PURCHASE_RETURN_IMPORT_UNEXPECTED_ERROR("message.purchase.return.import.unexpected.error"),
    MESSAGE_PURCHASE_RETURN_IMPORT_SUCCESS("message.purchase.return.import.success"),
    MESSAGE_PURCHASE_RETURN_IMPORT_FAILED("message.purchase.return.import.failed"),
    MESSAGE_PURCHASE_RETURN_RECORDED_SUCCESSFULLY("message.purchase.return.recorded.successfully"),

    // Inventory Transfer messages
    MESSAGE_CREATE_INVENTORY_TRANSFER_INVALID_REQUEST("message.create.inventory.transfer.invalid.request"),
    MESSAGE_INVENTORY_TRANSFER_FROM_LOCATION_NOT_FOUND("message.inventory.transfer.from.location.not.found"),
    MESSAGE_INVENTORY_TRANSFER_TO_LOCATION_NOT_FOUND("message.inventory.transfer.to.location.not.found"),
    MESSAGE_INVENTORY_TRANSFER_CREATED_SUCCESSFULLY("message.inventory.transfer.created.successfully"),
    MESSAGE_INVENTORY_TRANSFER_NOT_FOUND("message.inventory.transfer.not.found"),
    MESSAGE_INVENTORY_TRANSFER_NOT_IN_TRANSIT("message.inventory.transfer.not.in.transit"),
    MESSAGE_INVENTORY_TRANSFER_TRANSIT_REQUIRES_DISPATCH("message.inventory.transfer.transit.requires.dispatch"),
    MESSAGE_INVENTORY_TRANSFER_DISPATCH_NOT_READY("message.inventory.transfer.dispatch.not.ready"),
    MESSAGE_INVENTORY_TRANSFER_COMPLETE_REQUIRES_RECEIVER_ACK("message.inventory.transfer.complete.requires.receiver.ack"),
    MESSAGE_INVENTORY_TRANSFER_STATUS_CHANGE_NOT_ALLOWED("message.inventory.transfer.status.change.not.allowed"),
    MESSAGE_INVENTORY_TRANSFER_SOURCE_ITEM_NOT_FOUND("message.inventory.transfer.source.item.not.found"),
    MESSAGE_INVENTORY_TRANSFER_COMPLETED_SUCCESSFULLY("message.inventory.transfer.completed.successfully"),
    MESSAGE_INVENTORY_TRANSFER_RETRIEVED_SUCCESSFULLY("message.inventory.transfer.retrieved.successfully"),
    MESSAGE_INVENTORY_TRANSFER_UPDATE_INVALID("message.inventory.transfer.update.invalid"),
    MESSAGE_INVENTORY_TRANSFER_NOT_EDITABLE("message.inventory.transfer.not.editable"),
    MESSAGE_INVENTORY_TRANSFER_UPDATED_SUCCESSFULLY("message.inventory.transfer.updated.successfully"),
    MESSAGE_INVENTORY_TRANSFER_DELETED_SUCCESSFULLY("message.inventory.transfer.deleted.successfully"),
    MESSAGE_INVENTORY_TRANSFER_INVALID_MULTIPLE_FILTERS_REQUEST("message.inventory.transfer.invalid.multiple.filters.request"),
    MESSAGE_INVENTORY_TRANSFER_REQUEST_IS_NULL("message.inventory.transfer.request.is.null"),
    MESSAGE_INVENTORY_TRANSFER_PAGE_NEGATIVE("message.inventory.transfer.page.negative"),
    MESSAGE_INVENTORY_TRANSFER_SIZE_INVALID("message.inventory.transfer.size.invalid"),
    MESSAGE_INVENTORY_TRANSFER_PAGE_OUT_OF_BOUNDS("message.inventory.transfer.page.out.of.bounds"),
    
    // Inventory Transfer validation messages
    MESSAGE_CREATE_INVENTORY_TRANSFER_REQUEST_IS_NULL("message.create.inventory.transfer.request.is.null"),
    MESSAGE_CREATE_INVENTORY_TRANSFER_NUMBER_INVALID("message.create.inventory.transfer.number.invalid"),
    MESSAGE_CREATE_INVENTORY_TRANSFER_PRODUCT_ID_INVALID("message.create.inventory.transfer.product.id.invalid"),
    MESSAGE_CREATE_INVENTORY_TRANSFER_FROM_LOCATION_ID_INVALID("message.create.inventory.transfer.from.location.id.invalid"),
    MESSAGE_CREATE_INVENTORY_TRANSFER_TO_LOCATION_ID_INVALID("message.create.inventory.transfer.to.location.id.invalid"),
    MESSAGE_CREATE_INVENTORY_TRANSFER_SAME_LOCATIONS("message.create.inventory.transfer.same.locations"),
    MESSAGE_CREATE_INVENTORY_TRANSFER_QUANTITY_INVALID("message.create.inventory.transfer.quantity.invalid"),
    MESSAGE_CREATE_INVENTORY_TRANSFER_UNIT_COST_INVALID("message.create.inventory.transfer.unit.cost.invalid"),
    MESSAGE_CREATE_INVENTORY_TRANSFER_CREATED_BY_USER_ID_INVALID("message.create.inventory.transfer.created.by.user.id.invalid"),
    MESSAGE_EDIT_INVENTORY_TRANSFER_REQUEST_IS_NULL("message.edit.inventory.transfer.request.is.null"),
    MESSAGE_EDIT_INVENTORY_TRANSFER_ID_INVALID("message.edit.inventory.transfer.id.invalid"),
    MESSAGE_EDIT_INVENTORY_TRANSFER_PRODUCT_ID_INVALID("message.edit.inventory.transfer.product.id.invalid"),
    MESSAGE_EDIT_INVENTORY_TRANSFER_FROM_LOCATION_ID_INVALID("message.edit.inventory.transfer.from.location.id.invalid"),
    MESSAGE_EDIT_INVENTORY_TRANSFER_TO_LOCATION_ID_INVALID("message.edit.inventory.transfer.to.location.id.invalid"),
    MESSAGE_EDIT_INVENTORY_TRANSFER_SAME_LOCATIONS("message.edit.inventory.transfer.same.locations"),
    MESSAGE_EDIT_INVENTORY_TRANSFER_QUANTITY_INVALID("message.edit.inventory.transfer.quantity.invalid"),
    MESSAGE_EDIT_INVENTORY_TRANSFER_UPDATED_BY_USER_ID_INVALID("message.edit.inventory.transfer.updated.by.user.id.invalid"),

    // Stock Adjustment messages
    MESSAGE_STOCK_ADJUSTMENT_INSUFFICIENT_STOCK("message.stock.adjustment.insufficient.stock"),
    MESSAGE_STOCK_ADJUSTMENT_CREATED_SUCCESSFULLY("message.stock.adjustment.created.successfully"),
    MESSAGE_STOCK_ADJUSTMENT_NOT_FOUND("message.stock.adjustment.not.found"),
    MESSAGE_STOCK_ADJUSTMENT_RETRIEVED_SUCCESSFULLY("message.stock.adjustment.retrieved.successfully"),
    MESSAGE_STOCK_ADJUSTMENT_UPDATE_INVALID("message.stock.adjustment.update.invalid"),
    MESSAGE_STOCK_ADJUSTMENT_UPDATED_SUCCESSFULLY("message.stock.adjustment.updated.successfully"),
    MESSAGE_STOCK_ADJUSTMENT_DELETED_SUCCESSFULLY("message.stock.adjustment.deleted.successfully"),
    MESSAGE_STOCK_ADJUSTMENT_INVALID_MULTIPLE_FILTERS_REQUEST("message.stock.adjustment.invalid.multiple.filters.request"),
    MESSAGE_STOCK_ADJUSTMENT_PAGE_OUT_OF_BOUNDS("message.stock.adjustment.page.out.of.bounds"),
    MESSAGE_CREATE_STOCK_ADJUSTMENT_INVALID_REQUEST("message.create.stock.adjustment.invalid.request"),

    // Sales Order messages
    MESSAGE_CREATE_SALES_ORDER_INVALID_REQUEST("message.create.sales.order.invalid.request"),
    MESSAGE_SALES_ORDER_CREATED_SUCCESSFULLY("message.sales.order.created.successfully"),
    MESSAGE_SALES_ORDER_NOT_FOUND("message.sales.order.not.found"),
    MESSAGE_SALES_ORDER_RETRIEVED_SUCCESSFULLY("message.sales.order.retrieved.successfully"),
    MESSAGE_UPDATE_SALES_ORDER_INVALID_REQUEST("message.update.sales.order.invalid.request"),
    MESSAGE_SALES_ORDER_NOT_EDITABLE("message.sales.order.not.editable"),
    MESSAGE_SALES_ORDER_UPDATED_SUCCESSFULLY("message.sales.order.updated.successfully"),
    MESSAGE_FULFILL_SALES_ORDER_INVALID_REQUEST("message.fulfill.sales.order.invalid.request"),
    MESSAGE_FULFILL_SALES_ORDER_REQUEST_IS_NULL("message.fulfill.sales.order.request.is.null"),
    MESSAGE_SALES_ORDER_ID_SUPPLIED_IS_INVALID_FOR_FULLFILLMENT("message.sales.order.id.supplied.is.invalid.for.fullfillment"),
    MESSAGE_SALES_ORDER_NOT_FULFILLABLE("message.sales.order.not.fulfillable"),
    MESSAGE_SALES_ORDER_FULFILLED_SUCCESSFULLY("message.sales.order.fulfilled.successfully"),
    MESSAGE_SALES_ORDER_PARTIALLY_FULFILLED("message.sales.order.partially.fulfilled"),
    MESSAGE_SALES_ORDER_CANNOT_DELETE_FULFILLED("message.sales.order.cannot.delete.fulfilled"),
    MESSAGE_SALES_ORDER_DELETED_SUCCESSFULLY("message.sales.order.deleted.successfully"),
    MESSAGE_SALES_ORDER_INVALID_MULTIPLE_FILTERS_REQUEST("message.sales.order.invalid.multiple.filters.request"),
    MESSAGE_SALES_ORDER_PAGE_OUT_OF_BOUNDS("message.sales.order.page.out.of.bounds"),
    MESSAGE_SALES_ORDER_FULFILLMENT_FAILED("message.sales.order.fulfillment.failed"),
    MESSAGE_SALES_ORDER_DISPATCH_NOT_READY("message.sales.order.dispatch.not.ready"),
    MESSAGE_SALES_ORDER_DISPATCH_REQUIRES_TRIP("message.sales.order.dispatch.requires.trip"),
    MESSAGE_SALES_ORDER_DISPATCH_STARTED("message.sales.order.dispatch.started"),
    MESSAGE_SALES_ORDER_COMPLETE_REQUIRES_RECEIVER_ACK("message.sales.order.complete.requires.receiver.ack"),
    MESSAGE_SALES_ORDER_DELIVERY_COMPLETED("message.sales.order.delivery.completed"),

    // Sales Reservation messages
    MESSAGE_CREATE_SALES_RESERVATION_INVALID_REQUEST("message.create.sales.reservation.invalid.request"),
    MESSAGE_SALES_RESERVATION_NOT_FOUND("message.sales.reservation.not.found"),
    MESSAGE_SALES_RESERVATION_CREATED_SUCCESSFULLY("message.sales.reservation.created.successfully"),
    MESSAGE_SALES_RESERVATION_RETRIEVED_SUCCESSFULLY("message.sales.reservation.retrieved.successfully"),
    MESSAGE_SALES_RESERVATION_UPDATED_SUCCESSFULLY("message.sales.reservation.updated.successfully"),
    MESSAGE_SALES_RESERVATION_DELETED_SUCCESSFULLY("message.sales.reservation.deleted.successfully"),
    MESSAGE_SALES_RESERVATION_INSUFFICIENT_STOCK("message.sales.reservation.insufficient.stock"),
    MESSAGE_SALES_RESERVATION_NOT_EDITABLE("message.sales.reservation.not.editable"),
    MESSAGE_SALES_RESERVATION_INVALID_MULTIPLE_FILTERS_REQUEST("message.sales.reservation.invalid.multiple.filters.request"),
    MESSAGE_SALES_RESERVATION_PAGE_OUT_OF_BOUNDS("message.sales.reservation.page.out.of.bounds"),
    MESSAGE_UPDATE_SALES_RESERVATION_INVALID_REQUEST("message.update.sales.reservation.invalid.request"),

    // Sales Order Line messages
    MESSAGE_CREATE_SALES_ORDER_LINE_INVALID_REQUEST("message.create.sales.order.line.invalid.request"),
    MESSAGE_SALES_ORDER_LINE_CREATED_SUCCESSFULLY("message.sales.order.line.created.successfully"),
    MESSAGE_SALES_ORDER_LINE_NOT_FOUND("message.sales.order.line.not.found"),
    MESSAGE_SALES_ORDER_LINE_RETRIEVED_SUCCESSFULLY("message.sales.order.line.retrieved.successfully"),
    MESSAGE_UPDATE_SALES_ORDER_LINE_INVALID_REQUEST("message.update.sales.order.line.invalid.request"),
    MESSAGE_SALES_ORDER_LINE_UPDATED_SUCCESSFULLY("message.sales.order.line.updated.successfully"),
    MESSAGE_SALES_ORDER_LINE_DELETED_SUCCESSFULLY("message.sales.order.line.deleted.successfully"),
    MESSAGE_SALES_ORDER_LINE_INVALID_MULTIPLE_FILTERS_REQUEST("message.sales.order.line.invalid.multiple.filters.request"),
    MESSAGE_SALES_ORDER_LINE_PAGE_OUT_OF_BOUNDS("message.sales.order.line.page.out.of.bounds"),

    // Purchase Requisition messages
    MESSAGE_PURCHASE_REQUISITION_NOT_FOUND("message.purchase.requisition.not.found"),
    MESSAGE_PURCHASE_REQUISITION_ALREADY_EXISTS("message.purchase.requisition.already.exists"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_INVALID_REQUEST("message.create.purchase.requisition.invalid.request"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_REQUEST_IS_NULL("message.create.purchase.requisition.request.is.null"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_ORGANIZATION_ID_REQUIRED("message.create.purchase.requisition.organization.id.required"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_DEPARTMENT_ID_REQUIRED("message.create.purchase.requisition.department.id.required"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_REQUESTED_BY_USER_ID_REQUIRED("message.create.purchase.requisition.requested.by.user.id.required"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_PURPOSE_REQUIRED("message.create.purchase.requisition.purpose.required"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_LINES_REQUIRED("message.create.purchase.requisition.lines.required"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_LINE_PRODUCT_ID_REQUIRED("message.create.purchase.requisition.line.product.id.required"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_LINE_PRODUCT_NOT_FOUND("message.create.purchase.requisition.line.product.not.found"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_LINE_QUANTITY_REQUIRED("message.create.purchase.requisition.line.quantity.required"),
    MESSAGE_CREATE_PURCHASE_REQUISITION_LINE_UOM_REQUIRED("message.create.purchase.requisition.line.uom.required"),
    MESSAGE_PURCHASE_REQUISITION_CREATED_SUCCESSFULLY("message.purchase.requisition.created.successfully"),
    MESSAGE_PURCHASE_REQUISITION_RETRIEVED_SUCCESSFULLY("message.purchase.requisition.retrieved.successfully"),
    MESSAGE_EDIT_PURCHASE_REQUISITION_REQUEST_IS_NULL("message.edit.purchase.requisition.request.is.null"),
    MESSAGE_EDIT_PURCHASE_REQUISITION_ID_REQUIRED("message.edit.purchase.requisition.id.required"),
    MESSAGE_PURCHASE_REQUISITION_NOT_EDITABLE("message.purchase.requisition.not.editable"),
    MESSAGE_PURCHASE_REQUISITION_UPDATED_SUCCESSFULLY("message.purchase.requisition.updated.successfully"),
    MESSAGE_PURCHASE_REQUISITION_DELETED_SUCCESSFULLY("message.purchase.requisition.deleted.successfully"),
    MESSAGE_PURCHASE_REQUISITION_INVALID_MULTIPLE_FILTERS_REQUEST("message.purchase.requisition.invalid.multiple.filters.request"),
    MESSAGE_PURCHASE_REQUISITION_PAGE_OUT_OF_BOUNDS("message.purchase.requisition.page.out.of.bounds"),

    // Purchase Requisition workflow messages
    MESSAGE_PURCHASE_REQUISITION_SUBMITTED_SUCCESSFULLY("message.purchase.requisition.submitted.successfully"),
    MESSAGE_PURCHASE_REQUISITION_NOT_SUBMITTABLE("message.purchase.requisition.not.submittable"),
    MESSAGE_PURCHASE_REQUISITION_APPROVED_SUCCESSFULLY("message.purchase.requisition.approved.successfully"),
    MESSAGE_PURCHASE_REQUISITION_NOT_APPROVABLE("message.purchase.requisition.not.approvable"),
    MESSAGE_APPROVE_PURCHASE_REQUISITION_REQUEST_IS_NULL("message.approve.purchase.requisition.request.is.null"),
    MESSAGE_APPROVE_PURCHASE_REQUISITION_ID_REQUIRED("message.approve.purchase.requisition.id.required"),
    MESSAGE_APPROVE_PURCHASE_REQUISITION_APPROVED_BY_REQUIRED("message.approve.purchase.requisition.approved.by.required"),
    MESSAGE_PURCHASE_REQUISITION_REJECTED_SUCCESSFULLY("message.purchase.requisition.rejected.successfully"),
    MESSAGE_PURCHASE_REQUISITION_NOT_REJECTABLE("message.purchase.requisition.not.rejectable"),
    MESSAGE_REJECT_PURCHASE_REQUISITION_REQUEST_IS_NULL("message.reject.purchase.requisition.request.is.null"),
    MESSAGE_REJECT_PURCHASE_REQUISITION_ID_REQUIRED("message.reject.purchase.requisition.id.required"),
    MESSAGE_REJECT_PURCHASE_REQUISITION_REJECTED_BY_REQUIRED("message.reject.purchase.requisition.rejected.by.required"),
    MESSAGE_REJECT_PURCHASE_REQUISITION_REASON_REQUIRED("message.reject.purchase.requisition.reason.required"),
    MESSAGE_PURCHASE_REQUISITION_CANCELLED_SUCCESSFULLY("message.purchase.requisition.cancelled.successfully"),
    MESSAGE_PURCHASE_REQUISITION_NOT_CANCELLABLE("message.purchase.requisition.not.cancellable"),
    MESSAGE_CANCEL_PURCHASE_REQUISITION_REQUEST_IS_NULL("message.cancel.purchase.requisition.request.is.null"),
    MESSAGE_CANCEL_PURCHASE_REQUISITION_ID_REQUIRED("message.cancel.purchase.requisition.id.required"),
    MESSAGE_CANCEL_PURCHASE_REQUISITION_CANCELLED_BY_REQUIRED("message.cancel.purchase.requisition.cancelled.by.required"),
    MESSAGE_CANCEL_PURCHASE_REQUISITION_REASON_REQUIRED("message.cancel.purchase.requisition.reason.required"),
    MESSAGE_PURCHASE_REQUISITION_CLOSED_SUCCESSFULLY("message.purchase.requisition.closed.successfully"),

    // Purchase Requisition fulfillment messages
    MESSAGE_FULFILL_PURCHASE_REQUISITION_INVALID_REQUEST("message.fulfill.purchase.requisition.invalid.request"),
    MESSAGE_FULFILL_PURCHASE_REQUISITION_REQUEST_IS_NULL("message.fulfill.purchase.requisition.request.is.null"),
    MESSAGE_FULFILL_PURCHASE_REQUISITION_LINE_NOT_FOUND("message.fulfill.purchase.requisition.line.not.found"),
    MESSAGE_FULFILL_PURCHASE_REQUISITION_QUANTITY_EXCEEDS_REMAINING("message.fulfill.purchase.requisition.quantity.exceeds.remaining"),
    MESSAGE_FULFILL_PURCHASE_REQUISITION_NOT_APPROVED("message.fulfill.purchase.requisition.not.approved"),
    MESSAGE_PURCHASE_REQUISITION_LINE_FULFILLED_SUCCESSFULLY("message.purchase.requisition.line.fulfilled.successfully"),
    MESSAGE_PURCHASE_REQUISITION_FULFILLED_SUCCESSFULLY("message.purchase.requisition.fulfilled.successfully"),
    MESSAGE_PURCHASE_REQUISITION_PARTIALLY_FULFILLED("message.purchase.requisition.partially.fulfilled"),

    // Purchase Requisition to PO conversion messages
    MESSAGE_CREATE_PO_FROM_PR_INVALID_REQUEST("message.create.po.from.pr.invalid.request"),
    MESSAGE_CREATE_PO_FROM_PR_REQUEST_IS_NULL("message.create.po.from.pr.request.is.null"),
    MESSAGE_CREATE_PO_FROM_PR_NOT_APPROVED("message.create.po.from.pr.not.approved"),
    MESSAGE_CREATE_PO_FROM_PR_NO_ELIGIBLE_LINES("message.create.po.from.pr.no.eligible.lines"),
    MESSAGE_CREATE_PO_FROM_PR_SUPPLIER_REQUIRED("message.create.po.from.pr.supplier.required"),
    MESSAGE_CREATE_PO_FROM_PR_SUCCESSFUL("message.create.po.from.pr.successful"),

    // Purchase Requisition amendment messages
    MESSAGE_PURCHASE_REQUISITION_AMENDMENT_CREATED_SUCCESSFULLY("message.purchase.requisition.amendment.created.successfully"),
    MESSAGE_PURCHASE_REQUISITION_REQUIRES_AMENDMENT("message.purchase.requisition.requires.amendment"),

    // Logistics Route Stop messages
    MESSAGE_ROUTE_STOP_INVALID_REQUEST("message.route.stop.invalid.request"),
    MESSAGE_ROUTE_STOP_CONTEXT_TYPE_REQUIRED("message.route.stop.context.type.required"),
    MESSAGE_ROUTE_STOP_CONTEXT_ID_REQUIRED("message.route.stop.context.id.required"),
    MESSAGE_ROUTE_STOP_ORGANIZATION_ID_REQUIRED("message.route.stop.organization.id.required"),
    MESSAGE_ROUTE_STOP_NOT_FOUND("message.route.stop.not.found"),
    MESSAGE_ROUTE_STOP_REPLACED_SUCCESSFULLY("message.route.stop.replaced.successfully"),
    MESSAGE_ROUTE_STOP_RETRIEVED_SUCCESSFULLY("message.route.stop.retrieved.successfully"),
    MESSAGE_ROUTE_STOP_DELETED_SUCCESSFULLY("message.route.stop.deleted.successfully"),

    // Inventory Integration Credential messages
    MESSAGE_INTEGRATION_CREDENTIAL_INVALID_REQUEST("message.integration.credential.invalid.request"),
    MESSAGE_INTEGRATION_CREDENTIAL_ORG_ID_REQUIRED("message.integration.credential.org.id.required"),
    MESSAGE_INTEGRATION_CREDENTIAL_LABEL_REQUIRED("message.integration.credential.label.required"),
    MESSAGE_INTEGRATION_CREDENTIAL_UPDATE_INVALID("message.integration.credential.update.invalid"),
    MESSAGE_INTEGRATION_CREDENTIAL_NOT_FOUND("message.integration.credential.not.found"),
    MESSAGE_INTEGRATION_CREDENTIAL_SUSPENDED("message.integration.credential.suspended"),
    MESSAGE_INTEGRATION_CREDENTIAL_CREATED_SUCCESSFULLY("message.integration.credential.created.successfully"),
    MESSAGE_INTEGRATION_CREDENTIAL_UPDATED_SUCCESSFULLY("message.integration.credential.updated.successfully"),
    MESSAGE_INTEGRATION_CREDENTIAL_DELETED_SUCCESSFULLY("message.integration.credential.deleted.successfully"),
    MESSAGE_INTEGRATION_CREDENTIAL_RETRIEVED_SUCCESSFULLY("message.integration.credential.retrieved.successfully"),

    // Cross-Dock Dispatch messages
    MESSAGE_DISPATCH_INGEST_INVALID_REQUEST("message.dispatch.ingest.invalid.request"),
    MESSAGE_DISPATCH_INGEST_API_KEY_REQUIRED("message.dispatch.ingest.api.key.required"),
    MESSAGE_DISPATCH_INGEST_EXTERNAL_ID_REQUIRED("message.dispatch.ingest.external.id.required"),
    MESSAGE_DISPATCH_INGEST_DUPLICATE("message.dispatch.ingest.duplicate"),
    MESSAGE_DISPATCH_INGEST_CREATED_SUCCESSFULLY("message.dispatch.ingest.created.successfully"),
    MESSAGE_DISPATCH_GRV_CALLBACK_RECEIVED("message.dispatch.grv.callback.received"),
    MESSAGE_CROSS_DOCK_DISPATCH_NOT_FOUND("message.cross.dock.dispatch.not.found"),
    MESSAGE_CROSS_DOCK_DISPATCH_RETRIEVED_SUCCESSFULLY("message.cross.dock.dispatch.retrieved.successfully");

    private final String code;
}
