-- Organization directory notifications (email enabled; SMS/WhatsApp prepared for future activation).
INSERT INTO notification_template (
    template_key,
    description,
    channels,
    channel_delivery_enabled,
    email_subject,
    email_body_html,
    sms_body,
    in_app_title,
    in_app_body,
    is_active,
    entity_status,
    created_at,
    updated_at
)
VALUES (
    'ORG_BRANCH_CREATED',
    'Notifies organization contacts when a branch is created',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    '{{organizationName}} - branch created: {{branchName}}',
    '<p>Hello {{contactName}},</p><p>A new branch has been added to <strong>{{organizationName}}</strong>.</p><p><strong>Branch name:</strong> {{branchName}}<br/><strong>Branch code:</strong> {{branchCode}}<br/><strong>Region:</strong> {{branchRegion}}<br/><strong>Phone:</strong> {{branchPhoneNumber}}<br/><strong>Email:</strong> {{branchEmail}}</p><p><strong>Performed by:</strong> {{performedBy}}</p><p>You can review your organization directory details after sign in: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    NULL,
    'Branch created',
    'A new branch ({{branchName}}) was created for {{organizationName}}.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'ORG_AGENT_CREATED',
    'Notifies organization contacts when an agent is created',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    '{{organizationName}} - agent created: {{agentName}}',
    '<p>Hello {{contactName}},</p><p>A new agent record has been created for <strong>{{organizationName}}</strong>.</p><p><strong>Agent name:</strong> {{agentName}}<br/><strong>Agent kind:</strong> {{agentKind}}<br/><strong>Agent type:</strong> {{agentType}}<br/><strong>Role:</strong> {{agentRole}}<br/><strong>Phone:</strong> {{agentPhoneNumber}}<br/><strong>Email:</strong> {{agentEmail}}</p><p><strong>Performed by:</strong> {{performedBy}}</p><p>Sign in to manage directory records: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    NULL,
    'Agent created',
    'A new agent ({{agentName}}) was created for {{organizationName}}.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'ORG_CUSTOMER_LINKED',
    'Notifies both organisations when a supplier–customer link is created',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    '{{organizationName}} — linked with {{linkedOrganizationName}}',
    '<p>Hello {{contactName}},</p><p>Your organisation <strong>{{organizationName}}</strong> is now linked with <strong>{{linkedOrganizationName}}</strong> on Project LX LDMS (supplier: {{supplierName}}, customer: {{customerName}}).</p><p><strong>Counterpart email:</strong> {{linkedOrganizationEmail}}<br/><strong>Performed by:</strong> {{performedBy}}</p><p>Sign in to review the relationship: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    NULL,
    'Organisation link created',
    '{{organizationName}} is now linked with {{linkedOrganizationName}}.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'ORG_CLEARING_AGENT_LINKED',
    'Notifies both organisations when a supplier–clearing agent link is created',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    '{{organizationName}} — linked with {{linkedOrganizationName}}',
    '<p>Hello {{contactName}},</p><p>Your organisation <strong>{{organizationName}}</strong> is now linked with <strong>{{linkedOrganizationName}}</strong> on Project LX LDMS (supplier: {{supplierName}}, clearing agent: {{clearingAgentName}}).</p><p><strong>Counterpart email:</strong> {{linkedOrganizationEmail}}<br/><strong>Performed by:</strong> {{performedBy}}</p><p>Sign in to review the relationship: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    NULL,
    'Organisation link created',
    '{{organizationName}} is now linked with {{linkedOrganizationName}}.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'ORG_TRANSPORTER_LINKED',
    'Notifies both organisations when a supplier–transporter link is created',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    '{{organizationName}} — linked with {{linkedOrganizationName}}',
    '<p>Hello {{contactName}},</p><p>Your organisation <strong>{{organizationName}}</strong> is now linked with <strong>{{linkedOrganizationName}}</strong> on Project LX LDMS (supplier: {{supplierName}}, transporter: {{transporterName}}).</p><p><strong>Counterpart email:</strong> {{linkedOrganizationEmail}}<br/><strong>Performed by:</strong> {{performedBy}}</p><p>Sign in to review the relationship: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    NULL,
    'Organisation link created',
    '{{organizationName}} is now linked with {{linkedOrganizationName}}.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
)
ON DUPLICATE KEY UPDATE
    description = VALUES(description),
    channels = VALUES(channels),
    channel_delivery_enabled = VALUES(channel_delivery_enabled),
    email_subject = VALUES(email_subject),
    email_body_html = VALUES(email_body_html),
    sms_body = VALUES(sms_body),
    in_app_title = VALUES(in_app_title),
    in_app_body = VALUES(in_app_body),
    is_active = VALUES(is_active),
    updated_at = NOW(6);
