-- Password reset and password change confirmation templates referenced by ldms-user-management.

INSERT INTO notification_template (
    template_key,
    description,
    channels,
    channel_delivery_enabled,
    email_subject,
    email_body_html,
    sms_body,
    in_app_title,
    in_app_body,
    is_active,
    entity_status,
    created_at,
    updated_at
)
VALUES (
    'PASSWORD_RESET_REQUEST',
    'Email sent when a user requests a password reset link',
    JSON_ARRAY('EMAIL'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    'Reset your Project LX password',
    '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width,initial-scale=1.0" /></head><body style="margin:0;padding:0;background:#edf2f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#edf2f7"><tr><td align="center" style="padding:40px 16px"><table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:18px;overflow:hidden"><tr><td style="background:linear-gradient(135deg,#0f1c45 0%,#1b2a5e 50%,#2c3d85 100%);padding:32px 48px 30px"><table cellpadding="0" cellspacing="0"><tr><td style="background:#3b82f6;border-radius:10px;padding:10px 16px;font-size:20px;font-weight:800;color:#ffffff">LX</td><td style="padding-left:16px;vertical-align:middle"><div style="font-size:19px;font-weight:700;color:#ffffff">Project LX</div></td></tr></table></td></tr><tr><td height="4" style="background:linear-gradient(90deg,#3b82f6,#818cf8,#f97316);font-size:0">&nbsp;</td></tr><tr><td style="padding:38px 48px 44px"><table cellpadding="0" cellspacing="0" style="margin-bottom:26px"><tr><td style="background:#fef2f2;border:1.5px solid #fecaca;border-radius:20px;padding:6px 16px"><span style="font-size:11px;font-weight:700;color:#b91c1c">&#128274; PASSWORD RESET</span></td></tr></table><p style="margin:0 0 14px;font-size:27px;font-weight:700;color:#0f1c45">Hi {{firstName}},</p><p style="margin:0 0 26px;font-size:15px;color:#4a5568;line-height:1.8">We received a request to reset the password for your Project LX account (<strong>{{Email}}</strong>). If you made this request, use the button below to choose a new password.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:26px"><tr><td align="center"><table cellpadding="0" cellspacing="0"><tr><td style="background:linear-gradient(135deg,#dc2626,#b91c1c);border-radius:50px"><a href="{{resetLink}}" style="display:inline-block;padding:16px 52px;font-size:15px;font-weight:700;color:#ffffff;text-decoration:none">Reset my password &rarr;</a></td></tr></table></td></tr></table><p style="margin:0 0 12px;font-size:14px;color:#64748b;line-height:1.7">This link expires in 24 hours. If you did not request a reset, you can ignore this email — your password will stay the same.</p><p style="margin:0;font-size:13px;color:#94a3b8;word-break:break-all">Or copy this link: {{resetLink}}</p></td></tr></table></td></tr></table></body></html>',
    NULL,
    NULL,
    NULL,
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PASSWORD_RESET_REQUEST_SMS',
    'SMS alert when a password reset is requested',
    JSON_ARRAY('SMS'),
    JSON_OBJECT('EMAIL', FALSE, 'SMS', TRUE, 'WHATSAPP', FALSE),
    NULL,
    NULL,
    'Project LX: password reset requested for {{Email}}. If this was you, open {{resetLink}} within 24 hours. Otherwise ignore.',
    NULL,
    NULL,
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PASSWORD_RESET_IN_APP',
    'In-app notification when a password reset is requested',
    JSON_ARRAY('IN_APP'),
    JSON_OBJECT('EMAIL', FALSE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    NULL,
    NULL,
    NULL,
    'Password reset requested',
    'A password reset was requested for your Project LX account. Check your email for the secure link.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PASSWORD_CHANGE_CONFIRMATION',
    'Email confirming a successful password change',
    JSON_ARRAY('EMAIL'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    'Your Project LX password was changed',
    '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width,initial-scale=1.0" /></head><body style="margin:0;padding:0;background:#edf2f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#edf2f7"><tr><td align="center" style="padding:40px 16px"><table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:18px;overflow:hidden"><tr><td style="background:linear-gradient(135deg,#0f1c45 0%,#1b2a5e 50%,#2c3d85 100%);padding:32px 48px 30px"><table cellpadding="0" cellspacing="0"><tr><td style="background:#3b82f6;border-radius:10px;padding:10px 16px;font-size:20px;font-weight:800;color:#ffffff">LX</td><td style="padding-left:16px;vertical-align:middle"><div style="font-size:19px;font-weight:700;color:#ffffff">Project LX</div></td></tr></table></td></tr><tr><td height="4" style="background:linear-gradient(90deg,#3b82f6,#818cf8,#f97316);font-size:0">&nbsp;</td></tr><tr><td style="padding:38px 48px 44px"><table cellpadding="0" cellspacing="0" style="margin-bottom:26px"><tr><td style="background:#ecfdf5;border:1.5px solid #a7f3d0;border-radius:20px;padding:6px 16px"><span style="font-size:11px;font-weight:700;color:#065f46">&#10003; PASSWORD UPDATED</span></td></tr></table><p style="margin:0 0 14px;font-size:27px;font-weight:700;color:#0f1c45">Hi {{firstName}},</p><p style="margin:0 0 26px;font-size:15px;color:#4a5568;line-height:1.8">This confirms that the password for your Project LX account (<strong>{{Email}}</strong>) was changed successfully. You can sign in with your new password.</p><p style="margin:0;font-size:14px;color:#64748b;line-height:1.7">If you did not make this change, contact support immediately at <a href="mailto:support@projectlx.co.zw">support@projectlx.co.zw</a>.</p></td></tr></table></td></tr></table></body></html>',
    NULL,
    NULL,
    NULL,
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PASSWORD_CHANGE_CONFIRMATION_SMS',
    'SMS alert confirming a password change',
    JSON_ARRAY('SMS'),
    JSON_OBJECT('EMAIL', FALSE, 'SMS', TRUE, 'WHATSAPP', FALSE),
    NULL,
    NULL,
    'Project LX: your password was changed for {{Email}}. If this was not you, contact support immediately.',
    NULL,
    NULL,
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PASSWORD_CHANGE_IN_APP',
    'In-app notification confirming a password change',
    JSON_ARRAY('IN_APP'),
    JSON_OBJECT('EMAIL', FALSE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    NULL,
    NULL,
    NULL,
    'Password changed',
    'Your Project LX password was updated. Sign in again if you are on another device.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
)
ON DUPLICATE KEY UPDATE
    description = VALUES(description),
    channels = VALUES(channels),
    channel_delivery_enabled = VALUES(channel_delivery_enabled),
    email_subject = VALUES(email_subject),
    email_body_html = VALUES(email_body_html),
    sms_body = VALUES(sms_body),
    in_app_title = VALUES(in_app_title),
    in_app_body = VALUES(in_app_body),
    is_active = VALUES(is_active),
    entity_status = VALUES(entity_status),
    updated_at = NOW(6);
