-- Inventory operational notifications: requisitions, purchase orders, transfers.
-- EMAIL, SMS, and WhatsApp enabled on unified templates used by ldms-inventory-management.

INSERT INTO notification_template (
    template_key,
    description,
    channels,
    channel_delivery_enabled,
    email_subject,
    email_body_html,
    sms_body,
    whatsapp_body,
    in_app_title,
    in_app_body,
    is_active,
    entity_status,
    created_at,
    updated_at
)
VALUES
(
    'PURCHASE_REQUISITION_SUBMITTED',
    'Notifies procurement approvers when a purchase requisition is submitted for approval',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', TRUE, 'WHATSAPP', TRUE),
    'Purchase requisition {{requisitionNumber}} awaiting approval',
    '<p>Hello {{contactName}},</p><p>{{lifecycleMessage}}</p><p><strong>Requisition:</strong> {{requisitionNumber}}</p><p>Review and approve in the platform portal: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    'Project LX: requisition {{requisitionNumber}} needs your approval. Sign in: {{signInLink}}',
    'Project LX: requisition {{requisitionNumber}} needs your approval. Sign in: {{signInLink}}',
    'Requisition submitted',
    'Requisition {{requisitionNumber}} is awaiting your approval.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PURCHASE_ORDER_RECEIVED',
    'Notifies supplier organisation users when a new purchase order is received',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', TRUE, 'WHATSAPP', TRUE),
    'New purchase order {{purchaseOrderNumber}} received',
    '<p>Hello {{contactName}},</p><p>{{lifecycleMessage}}</p><p><strong>Purchase order:</strong> {{purchaseOrderNumber}}<br/><strong>Order date:</strong> {{orderDate}}</p><p>View details: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    'Project LX: new PO {{purchaseOrderNumber}} received. View: {{signInLink}}',
    'Project LX: new PO {{purchaseOrderNumber}} received. View: {{signInLink}}',
    'Purchase order received',
    'Purchase order {{purchaseOrderNumber}} was raised for your organisation.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'INVENTORY_TRANSFER_REQUESTED',
    'Notifies destination warehouse approvers when an inventory transfer is requested',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', TRUE, 'WHATSAPP', TRUE),
    'Incoming transfer {{transferNumber}} requires attention',
    '<p>Hello {{contactName}},</p><p>{{lifecycleMessage}}</p><p><strong>Transfer:</strong> {{transferNumber}}<br/><strong>Quantity:</strong> {{quantity}}</p><p>Review in the platform portal: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    'Project LX: transfer {{transferNumber}} incoming. Review: {{signInLink}}',
    'Project LX: transfer {{transferNumber}} incoming. Review: {{signInLink}}',
    'Transfer requested',
    'Transfer {{transferNumber}} is heading to your warehouse.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'INVENTORY_TRANSFER_COMPLETED',
    'Notifies destination warehouse users when an inventory transfer is completed',
    JSON_ARRAY('EMAIL', 'SMS', 'WHATSAPP'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', TRUE, 'WHATSAPP', TRUE),
    'Transfer {{transferNumber}} completed',
    '<p>Hello {{contactName}},</p><p>{{lifecycleMessage}}</p><p><strong>Transfer:</strong> {{transferNumber}}<br/><strong>Quantity:</strong> {{quantity}}</p><p>View stock: <a href="{{signInLink}}">{{signInLink}}</a></p>',
    'Project LX: transfer {{transferNumber}} completed. View: {{signInLink}}',
    'Project LX: transfer {{transferNumber}} completed. View: {{signInLink}}',
    'Transfer completed',
    'Transfer {{transferNumber}} has been received at your warehouse.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PURCHASE_ORDER_CREATED_SUPPLIER_EMAIL',
    'Email to supplier organisation when a purchase order is created',
    JSON_ARRAY('EMAIL'),
    JSON_OBJECT('EMAIL', TRUE, 'SMS', FALSE, 'WHATSAPP', FALSE),
    'Purchase order {{purchaseOrderNumber}} from your customer',
    '<p>Hello,</p><p>You have received purchase order <strong>{{purchaseOrderNumber}}</strong>.</p><p><strong>Order date:</strong> {{orderDate}}<br/><strong>Expected date:</strong> {{expectedDate}}<br/><strong>Total:</strong> {{totalAmount}} {{currency}}</p><p>Please sign in to your Project LX portal to acknowledge and fulfil this order.</p>',
    NULL,
    NULL,
    'Purchase order received',
    'Purchase order {{purchaseOrderNumber}} was created.',
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PURCHASE_ORDER_CREATED_SUPPLIER_SMS',
    'SMS to supplier organisation when a purchase order is created',
    JSON_ARRAY('SMS'),
    JSON_OBJECT('EMAIL', FALSE, 'SMS', TRUE, 'WHATSAPP', FALSE),
    NULL,
    NULL,
    'Project LX: PO {{purchaseOrderNumber}} received. Expected {{expectedDate}}. Total {{totalAmount}} {{currency}}.',
    NULL,
    NULL,
    NULL,
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
),
(
    'PURCHASE_ORDER_CREATED_SUPPLIER_WHATSAPP',
    'WhatsApp to supplier organisation when a purchase order is created',
    JSON_ARRAY('WHATSAPP'),
    JSON_OBJECT('EMAIL', FALSE, 'SMS', FALSE, 'WHATSAPP', TRUE),
    NULL,
    NULL,
    'Project LX: PO {{purchaseOrderNumber}} received. Expected {{expectedDate}}. Total {{totalAmount}} {{currency}}.',
    'Project LX: PO {{purchaseOrderNumber}} received. Expected {{expectedDate}}. Total {{totalAmount}} {{currency}}.',
    NULL,
    NULL,
    1,
    'ACTIVE',
    NOW(6),
    NOW(6)
)
ON DUPLICATE KEY UPDATE
    description              = VALUES(description),
    channels                 = VALUES(channels),
    channel_delivery_enabled = VALUES(channel_delivery_enabled),
    email_subject            = VALUES(email_subject),
    email_body_html          = VALUES(email_body_html),
    sms_body                 = VALUES(sms_body),
    whatsapp_body            = VALUES(whatsapp_body),
    in_app_title             = VALUES(in_app_title),
    in_app_body              = VALUES(in_app_body),
    is_active                = VALUES(is_active),
    updated_at               = NOW(6);
