package projectlx.co.zw.shared_library.utils.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum FileType {
    NATIONAL_ID("NATIONAL_ID"),
    PASSPORT("PASSPORT"),
    COMPANY_REGISTRATION_CERTIFICATE("COMPANY_REGISTRATION_CERTIFICATE"),
    TAX_CLEARANCE_CERTIFICATE("TAX_CLEARANCE_CERTIFICATE"),
    BUSINESS_LICENSE("BUSINESS_LICENSE"),
    PROOF_OF_ADDRESS("PROOF_OF_ADDRESS"),
    INDUSTRY_SPECIFIC_LICENSE("INDUSTRY_SPECIFIC_LICENSE"),
    ORGANIZATION_LOGO("ORGANIZATION_LOGO"),
    PRODUCT("PRODUCT"),
    INSURANCE_CERTIFICATE("INSURANCE_CERTIFICATE"),
    ROADWORTHINESS_CERTIFICATE("ROADWORTHINESS_CERTIFICATE"),
    OPERATING_PERMIT("OPERATING_PERMIT"),
    VEHICLE_REGISTRATION("VEHICLE_REGISTRATION"),
    ROAD_LICENSE("ROAD_LICENSE"),
    GOODS_OPERATOR_LICENCE("GOODS_OPERATOR_LICENCE"),
    HAZARDOUS_SUBSTANCES_PERMIT("HAZARDOUS_SUBSTANCES_PERMIT"),
    FIRE_SAFETY_CLEARANCE("FIRE_SAFETY_CLEARANCE"),
    LEASE_HIRE_AGREEMENT("LEASE_HIRE_AGREEMENT"),
    DRIVER_LICENCE("DRIVER_LICENCE"),
    DEFENSIVE_DRIVING_CERTIFICATE("DEFENSIVE_DRIVING_CERTIFICATE"),
    DRIVER_MEDICAL_CERTIFICATE("DRIVER_MEDICAL_CERTIFICATE"),
    OTHER("OTHER");

    private final String displayName;
}
