package projectlx.co.zw.locationsmanagementservice.utils.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum I18Code {

    MESSAGE_ID_SUPPLIED_INVALID("message.id.supplied.invalid"),

    MESSAGE_CREATE_COUNTRY_INVALID_REQUEST("message.create.country.invalid.request"),
    MESSAGE_CREATE_COUNTRY_REQUEST_IS_NULL("message.create.country.request.is.null"),
    MESSAGE_CREATE_COUNTRY_NAME_MISSING("message.create.country.name.missing"),
    MESSAGE_CREATE_COUNTRY_ISO_ALPHA_2_CODE_MISSING("message.create.country.iso.alpha.2.code.missing"),
    MESSAGE_CREATE_COUNTRY_ISO_ALPHA_3_CODE_MISSING("message.create.country.iso.alpha.3.code.missing"),
    MESSAGE_CREATE_COUNTRY_DIAL_CODE_MISSING("message.create.country.dial.code.missing"),
    MESSAGE_CREATE_COUNTRY_TIMEZONE_MISSING("message.create.country.timezone.missing"),
    MESSAGE_CREATE_COUNTRY_CURRENCY_CODE_MISSING("message.create.country.currency.code.missing"),
    MESSAGE_CREATE_COUNTRY_GEO_COORDINATES_ID_MISSING("message.create.country.geo.coordinates.id.missing"),
    MESSAGE_CREATE_COUNTRY_NAME_INVALID("message.create.country.name.invalid"),
    MESSAGE_COUNTRY_ALREADY_EXISTS("message.country.already.exists"),
    MESSAGE_COUNTRY_CREATED_SUCCESSFULLY("message.country.created.successfully"),
    MESSAGE_COUNTRY_NOT_FOUND("message.country.not.found"),
    MESSAGE_COUNTRY_RETRIEVED_SUCCESSFULLY("message.country.retrieved.successfully"),
    MESSAGE_UPDATE_COUNTRY_INVALID_REQUEST("message.update.country.invalid.request"),
    MESSAGE_COUNTRY_UPDATED_SUCCESSFULLY("message.country.updated.successfully"),
    MESSAGE_COUNTRY_DELETED_SUCCESSFULLY("message.country.deleted.successfully"),

    // Province related messages
    MESSAGE_CREATE_PROVINCE_INVALID_REQUEST("message.create.province.invalid.request"),
    MESSAGE_CREATE_PROVINCE_REQUEST_IS_NULL("message.create.province.request.is.null"),
    MESSAGE_CREATE_PROVINCE_NAME_MISSING("message.create.province.name.missing"),
    MESSAGE_CREATE_PROVINCE_CODE_MISSING("message.create.province.code.missing"),
    MESSAGE_CREATE_PROVINCE_COUNTRY_ID_MISSING("message.create.province.country.id.missing"),
    MESSAGE_CREATE_PROVINCE_ADMINISTRATIVE_LEVEL_ID_MISSING("message.create.province.administrative.level.id.missing"),
    MESSAGE_CREATE_PROVINCE_GEO_COORDINATES_ID_MISSING("message.create.province.geo.coordinates.id.missing"),
    MESSAGE_PROVINCE_ALREADY_EXISTS("message.province.already.exists"),
    MESSAGE_PROVINCE_CREATED_SUCCESSFULLY("message.province.created.successfully"),
    MESSAGE_PROVINCE_NOT_FOUND("message.province.not.found"),
    MESSAGE_PROVINCE_RETRIEVED_SUCCESSFULLY("message.province.retrieved.successfully"),
    MESSAGE_UPDATE_PROVINCE_INVALID_REQUEST("message.update.province.invalid.request"),
    MESSAGE_UPDATE_PROVINCE_REQUEST_IS_NULL("message.update.province.request.is.null"),
    MESSAGE_UPDATE_PROVINCE_NAME_MISSING("message.update.province.name.missing"),
    MESSAGE_UPDATE_PROVINCE_CODE_MISSING("message.update.province.code.missing"),
    MESSAGE_UPDATE_PROVINCE_COUNTRY_ID_MISSING("message.update.province.country.id.missing"),
    MESSAGE_UPDATE_PROVINCE_ADMINISTRATIVE_LEVEL_ID_MISSING("message.update.province.administrative.level.id.missing"),
    MESSAGE_UPDATE_PROVINCE_GEO_COORDINATES_ID_MISSING("message.update.province.geo.coordinates.id.missing"),
    MESSAGE_PROVINCE_UPDATED_SUCCESSFULLY("message.province.updated.successfully"),
    MESSAGE_PROVINCE_DELETED_SUCCESSFULLY("message.province.deleted.successfully"),

    // District related messages
    MESSAGE_CREATE_DISTRICT_INVALID_REQUEST("message.create.district.invalid.request"),
    MESSAGE_CREATE_DISTRICT_REQUEST_IS_NULL("message.create.district.request.is.null"),
    MESSAGE_CREATE_DISTRICT_NAME_MISSING("message.create.district.name.missing"),
    MESSAGE_CREATE_DISTRICT_CODE_MISSING("message.create.district.code.missing"),
    MESSAGE_CREATE_DISTRICT_PROVINCE_ID_MISSING("message.create.district.province.id.missing"),
    MESSAGE_CREATE_DISTRICT_ADMINISTRATIVE_LEVEL_ID_MISSING("message.create.district.administrative.level.id.missing"),
    MESSAGE_CREATE_DISTRICT_GEO_COORDINATES_ID_MISSING("message.create.district.geo.coordinates.id.missing"),
    MESSAGE_DISTRICT_ALREADY_EXISTS("message.district.already.exists"),
    MESSAGE_DISTRICT_CREATED_SUCCESSFULLY("message.district.created.successfully"),
    MESSAGE_DISTRICT_NOT_FOUND("message.district.not.found"),
    MESSAGE_DISTRICT_RETRIEVED_SUCCESSFULLY("message.district.retrieved.successfully"),
    MESSAGE_UPDATE_DISTRICT_INVALID_REQUEST("message.update.district.invalid.request"),
    MESSAGE_UPDATE_DISTRICT_REQUEST_IS_NULL("message.update.district.request.is.null"),
    MESSAGE_UPDATE_DISTRICT_NAME_MISSING("message.update.district.name.missing"),
    MESSAGE_UPDATE_DISTRICT_CODE_MISSING("message.update.district.code.missing"),
    MESSAGE_UPDATE_DISTRICT_PROVINCE_ID_MISSING("message.update.district.province.id.missing"),
    MESSAGE_UPDATE_DISTRICT_ADMINISTRATIVE_LEVEL_ID_MISSING("message.update.district.administrative.level.id.missing"),
    MESSAGE_UPDATE_DISTRICT_GEO_COORDINATES_ID_MISSING("message.update.district.geo.coordinates.id.missing"),
    MESSAGE_DISTRICT_UPDATED_SUCCESSFULLY("message.district.updated.successfully"),
    MESSAGE_DISTRICT_DELETED_SUCCESSFULLY("message.district.deleted.successfully"),

    // Suburb related messages
    MESSAGE_CREATE_SUBURB_INVALID_REQUEST("message.create.suburb.invalid.request"),
    MESSAGE_CREATE_SUBURB_REQUEST_IS_NULL("message.create.suburb.request.is.null"),
    MESSAGE_CREATE_SUBURB_NAME_MISSING("message.create.suburb.name.missing"),
    MESSAGE_CREATE_SUBURB_CODE_MISSING("message.create.suburb.code.missing"),
    MESSAGE_CREATE_SUBURB_POSTAL_CODE_MISSING("message.create.suburb.postal.code.missing"),
    MESSAGE_CREATE_SUBURB_DISTRICT_ID_MISSING("message.create.suburb.district.id.missing"),
    MESSAGE_CREATE_SUBURB_GEO_COORDINATES_ID_MISSING("message.create.suburb.geo.coordinates.id.missing"),
    MESSAGE_CREATE_SUBURB_ADMINISTRATIVE_LEVEL_ID_MISSING("message.create.suburb.administrative.level.id.missing"),
    MESSAGE_SUBURB_ALREADY_EXISTS("message.suburb.already.exists"),
    MESSAGE_SUBURB_CREATED_SUCCESSFULLY("message.suburb.created.successfully"),
    MESSAGE_SUBURB_NOT_FOUND("message.suburb.not.found"),
    MESSAGE_SUBURB_RETRIEVED_SUCCESSFULLY("message.suburb.retrieved.successfully"),
    MESSAGE_UPDATE_SUBURB_INVALID_REQUEST("message.update.suburb.invalid.request"),
    MESSAGE_UPDATE_SUBURB_REQUEST_IS_NULL("message.update.suburb.request.is.null"),
    MESSAGE_UPDATE_SUBURB_NAME_MISSING("message.update.suburb.name.missing"),
    MESSAGE_UPDATE_SUBURB_CODE_MISSING("message.update.suburb.code.missing"),
    MESSAGE_UPDATE_SUBURB_POSTAL_CODE_MISSING("message.update.suburb.postal.code.missing"),
    MESSAGE_UPDATE_SUBURB_DISTRICT_ID_MISSING("message.update.suburb.district.id.missing"),
    MESSAGE_UPDATE_SUBURB_GEO_COORDINATES_ID_MISSING("message.update.suburb.geo.coordinates.id.missing"),
    MESSAGE_UPDATE_SUBURB_ADMINISTRATIVE_LEVEL_ID_MISSING("message.update.suburb.administrative.level.id.missing"),
    MESSAGE_SUBURB_UPDATED_SUCCESSFULLY("message.suburb.updated.successfully"),
    MESSAGE_SUBURB_DELETED_SUCCESSFULLY("message.suburb.deleted.successfully"),

    // Address related messages
    MESSAGE_CREATE_ADDRESS_INVALID_REQUEST("message.create.address.invalid.request"),
    MESSAGE_CREATE_ADDRESS_REQUEST_IS_NULL("message.create.address.request.is.null"),
    MESSAGE_CREATE_ADDRESS_LINE1_MISSING("message.create.address.line1.missing"),
    MESSAGE_CREATE_ADDRESS_POSTAL_CODE_MISSING("message.create.address.postal.code.missing"),
    MESSAGE_CREATE_ADDRESS_SUBURB_ID_MISSING("message.create.address.suburb.id.missing"),
    MESSAGE_CREATE_ADDRESS_GEO_COORDINATES_ID_MISSING("message.create.address.geo.coordinates.id.missing"),
    MESSAGE_ADDRESS_ALREADY_EXISTS("message.address.already.exists"),
    MESSAGE_ADDRESS_CREATED_SUCCESSFULLY("message.address.created.successfully"),
    MESSAGE_ADDRESS_NOT_FOUND("message.address.not.found"),
    MESSAGE_ADDRESS_RETRIEVED_SUCCESSFULLY("message.address.retrieved.successfully"),
    MESSAGE_UPDATE_ADDRESS_INVALID_REQUEST("message.update.address.invalid.request"),
    MESSAGE_UPDATE_ADDRESS_REQUEST_IS_NULL("message.update.address.request.is.null"),
    MESSAGE_UPDATE_ADDRESS_LINE1_MISSING("message.update.address.line1.missing"),
    MESSAGE_UPDATE_ADDRESS_POSTAL_CODE_MISSING("message.update.address.postal.code.missing"),
    MESSAGE_UPDATE_ADDRESS_SUBURB_ID_MISSING("message.update.address.suburb.id.missing"),
    MESSAGE_UPDATE_ADDRESS_GEO_COORDINATES_ID_MISSING("message.update.address.geo.coordinates.id.missing"),
    MESSAGE_ADDRESS_UPDATED_SUCCESSFULLY("message.address.updated.successfully"),
    MESSAGE_ADDRESS_DELETED_SUCCESSFULLY("message.address.deleted.successfully"),

    // Language related messages
    MESSAGE_CREATE_LANGUAGE_INVALID_REQUEST("message.create.language.invalid.request"),
    MESSAGE_CREATE_LANGUAGE_REQUEST_IS_NULL("message.create.language.request.is.null"),
    MESSAGE_CREATE_LANGUAGE_NAME_MISSING("message.create.language.name.missing"),
    MESSAGE_CREATE_LANGUAGE_ISO_CODE_MISSING("message.create.language.iso.code.missing"),
    MESSAGE_CREATE_LANGUAGE_NATIVE_NAME_MISSING("message.create.language.native.name.missing"),
    MESSAGE_LANGUAGE_ALREADY_EXISTS("message.language.already.exists"),
    MESSAGE_LANGUAGE_CREATED_SUCCESSFULLY("message.language.created.successfully"),
    MESSAGE_LANGUAGE_NOT_FOUND("message.language.not.found"),
    MESSAGE_LANGUAGE_RETRIEVED_SUCCESSFULLY("message.language.retrieved.successfully"),
    MESSAGE_UPDATE_LANGUAGE_INVALID_REQUEST("message.update.language.invalid.request"),
    MESSAGE_UPDATE_LANGUAGE_REQUEST_IS_NULL("message.update.language.request.is.null"),
    MESSAGE_UPDATE_LANGUAGE_NAME_MISSING("message.update.language.name.missing"),
    MESSAGE_UPDATE_LANGUAGE_ISO_CODE_MISSING("message.update.language.iso.code.missing"),
    MESSAGE_UPDATE_LANGUAGE_NATIVE_NAME_MISSING("message.update.language.native.name.missing"),
    MESSAGE_LANGUAGE_UPDATED_SUCCESSFULLY("message.language.updated.successfully"),
    MESSAGE_LANGUAGE_DELETED_SUCCESSFULLY("message.language.deleted.successfully"),
    MESSAGE_LANGUAGE_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.language.multiple.filters.request.is.null"),

    // Administrative Level related messages
    MESSAGE_CREATE_ADMINISTRATIVE_LEVEL_INVALID_REQUEST("message.create.administrative.level.invalid.request"),
    MESSAGE_CREATE_ADMINISTRATIVE_LEVEL_REQUEST_IS_NULL("message.create.administrative.level.request.is.null"),
    MESSAGE_CREATE_ADMINISTRATIVE_LEVEL_NAME_MISSING("message.create.administrative.level.name.missing"),
    MESSAGE_CREATE_ADMINISTRATIVE_LEVEL_CODE_MISSING("message.create.administrative.level.code.missing"),
    MESSAGE_CREATE_ADMINISTRATIVE_LEVEL_LEVEL_MISSING("message.create.administrative.level.level.missing"),
    MESSAGE_CREATE_ADMINISTRATIVE_LEVEL_COUNTRY_ID_MISSING("message.create.administrative.level.country.id.missing"),
    MESSAGE_ADMINISTRATIVE_LEVEL_ALREADY_EXISTS("message.administrative.level.already.exists"),
    MESSAGE_ADMINISTRATIVE_LEVEL_CREATED_SUCCESSFULLY("message.administrative.level.created.successfully"),
    MESSAGE_ADMINISTRATIVE_LEVEL_NOT_FOUND("message.administrative.level.not.found"),
    MESSAGE_ADMINISTRATIVE_LEVEL_RETRIEVED_SUCCESSFULLY("message.administrative.level.retrieved.successfully"),
    MESSAGE_UPDATE_ADMINISTRATIVE_LEVEL_INVALID_REQUEST("message.update.administrative.level.invalid.request"),
    MESSAGE_UPDATE_ADMINISTRATIVE_LEVEL_REQUEST_IS_NULL("message.update.administrative.level.request.is.null"),
    MESSAGE_UPDATE_ADMINISTRATIVE_LEVEL_NAME_MISSING("message.update.administrative.level.name.missing"),
    MESSAGE_UPDATE_ADMINISTRATIVE_LEVEL_CODE_MISSING("message.update.administrative.level.code.missing"),
    MESSAGE_UPDATE_ADMINISTRATIVE_LEVEL_LEVEL_MISSING("message.update.administrative.level.level.missing"),
    MESSAGE_UPDATE_ADMINISTRATIVE_LEVEL_COUNTRY_ID_MISSING("message.update.administrative.level.country.id.missing"),
    MESSAGE_ADMINISTRATIVE_LEVEL_UPDATED_SUCCESSFULLY("message.administrative.level.updated.successfully"),
    MESSAGE_ADMINISTRATIVE_LEVEL_DELETED_SUCCESSFULLY("message.administrative.level.deleted.successfully"),

    // Localized Name related messages
    MESSAGE_CREATE_LOCALIZED_NAME_INVALID_REQUEST("message.create.localized.name.invalid.request"),
    MESSAGE_CREATE_LOCALIZED_NAME_REQUEST_IS_NULL("message.create.localized.name.request.is.null"),
    MESSAGE_CREATE_LOCALIZED_NAME_VALUE_MISSING("message.create.localized.name.value.missing"),
    MESSAGE_CREATE_LOCALIZED_NAME_LANGUAGE_ID_MISSING("message.create.localized.name.language.id.missing"),
    MESSAGE_CREATE_LOCALIZED_NAME_REFERENCE_TYPE_MISSING("message.create.localized.name.reference.type.missing"),
    MESSAGE_CREATE_LOCALIZED_NAME_REFERENCE_ID_MISSING("message.create.localized.name.reference.id.missing"),
    MESSAGE_LOCALIZED_NAME_ALREADY_EXISTS("message.localized.name.already.exists"),
    MESSAGE_LOCALIZED_NAME_CREATED_SUCCESSFULLY("message.localized.name.created.successfully"),
    MESSAGE_LOCALIZED_NAME_NOT_FOUND("message.localized.name.not.found"),
    MESSAGE_LOCALIZED_NAME_RETRIEVED_SUCCESSFULLY("message.localized.name.retrieved.successfully"),
    MESSAGE_UPDATE_LOCALIZED_NAME_INVALID_REQUEST("message.update.localized.name.invalid.request"),
    MESSAGE_UPDATE_LOCALIZED_NAME_REQUEST_IS_NULL("message.update.localized.name.request.is.null"),
    MESSAGE_UPDATE_LOCALIZED_NAME_VALUE_MISSING("message.update.localized.name.value.missing"),
    MESSAGE_UPDATE_LOCALIZED_NAME_LANGUAGE_ID_MISSING("message.update.localized.name.language.id.missing"),
    MESSAGE_UPDATE_LOCALIZED_NAME_REFERENCE_TYPE_MISSING("message.update.localized.name.reference.type.missing"),
    MESSAGE_UPDATE_LOCALIZED_NAME_REFERENCE_ID_MISSING("message.update.localized.name.reference.id.missing"),
    MESSAGE_LOCALIZED_NAME_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.localized.name.multiple.filters.request.is.null"),
    MESSAGE_LOCALIZED_NAME_UPDATED_SUCCESSFULLY("message.localized.name.updated.successfully"),
    MESSAGE_LOCALIZED_NAME_DELETED_SUCCESSFULLY("message.localized.name.deleted.successfully"),
    MESSAGE_CREATE_LOCALIZED_NAME_INVALID_REFERENCE_TYPE("message.create.localized.name.invalid.reference.type"),
    MESSAGE_REFERENCE_ENTITY_NOT_FOUND("message.reference.entity.not.found"),

    // Geo Coordinates related messages
    MESSAGE_CREATE_GEO_COORDINATES_INVALID_REQUEST("message.create.geo.coordinates.invalid.request"),
    MESSAGE_CREATE_GEO_COORDINATES_REQUEST_IS_NULL("message.create.geo.coordinates.request.is.null"),
    MESSAGE_CREATE_GEO_COORDINATES_LATITUDE_MISSING("message.create.geo.coordinates.latitude.missing"),
    MESSAGE_CREATE_GEO_COORDINATES_LONGITUDE_MISSING("message.create.geo.coordinates.longitude.missing"),
    MESSAGE_GEO_COORDINATES_ALREADY_EXISTS("message.geo.coordinates.already.exists"),
    MESSAGE_GEO_COORDINATES_CREATED_SUCCESSFULLY("message.geo.coordinates.created.successfully"),
    MESSAGE_GEO_COORDINATES_NOT_FOUND("message.geo.coordinates.not.found"),
    MESSAGE_GEO_COORDINATES_RETRIEVED_SUCCESSFULLY("message.geo.coordinates.retrieved.successfully"),
    MESSAGE_UPDATE_GEO_COORDINATES_INVALID_REQUEST("message.update.geo.coordinates.invalid.request"),
    MESSAGE_UPDATE_GEO_COORDINATES_REQUEST_IS_NULL("message.update.geo.coordinates.request.is.null"),
    MESSAGE_UPDATE_GEO_COORDINATES_LATITUDE_MISSING("message.update.geo.coordinates.latitude.missing"),
    MESSAGE_UPDATE_GEO_COORDINATES_LONGITUDE_MISSING("message.update.geo.coordinates.longitude.missing"),
    MESSAGE_GEO_COORDINATES_UPDATED_SUCCESSFULLY("message.geo.coordinates.updated.successfully"),
    MESSAGE_GEO_COORDINATES_DELETED_SUCCESSFULLY("message.geo.coordinates.deleted.successfully");

    private final String code;
}
