server:
  port: 8098

spring:
  application:
    name: ldms-reporting-analytics
  datasource:
    url: jdbc:mysql://${DB_HOST:staging-db}:3306/ldms_analytics?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false

management:
  server:
    port: 9098
  tracing:
    sampling:
      probability: 0.1

logging:
  level:
    projectlx: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://staging-eureka:8761/eureka/}