server:
  port: 8092

spring:
  application:
    name: ldms-fuel-expenses
  datasource:
    url: jdbc:mysql://${DB_HOST:staging-db}:3306/ldms_fuel_expenses?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
clients:
  base-url:
    billing-payments: http://ldms-billing-payments
    trip-tracking: http://ldms-trip-tracking

management:
  server:
    port: 9092
  tracing:
    sampling:
      probability: 0.1

logging:
  level:
    projectlx: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://staging-eureka:8761/eureka/}