server:
  port: 8089

spring:
  application:
    name: ldms-fleet-management
  datasource:
    url: jdbc:mysql://${DB_HOST:staging-db}:3306/ldms_fleet_management?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
clients:
  base-url:
    documents-management: http://ldms-documents-management
    user-management: http://ldms-user-management

ldms:
  fleet:
    compliance-warning-days: 30

management:
  server:
    port: 9089
  tracing:
    sampling:
      probability: 0.1

logging:
  level:
    projectlx: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://staging-eureka:8761/eureka/}