server:
  port: 8085

spring:
  application:
    name: ldms-reference-config
  datasource:
    url: jdbc:mysql://${DB_HOST:staging-db}:3306/ldms_reference_config?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
  cache:
    type: redis
    redis:
      time-to-live: 21600000

management:
  server:
    port: 9085
  tracing:
    sampling:
      probability: 0.1

logging:
  level:
    projectlx: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://staging-eureka:8761/eureka/}