CREATE TABLE fleet_tracking_device (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  fleet_asset_id BIGINT NULL,
  fleet_driver_id BIGINT NULL,
  linked_user_id BIGINT NULL COMMENT 'Mobile app user when device_type=MOBILE_PHONE',
  device_type VARCHAR(50) NOT NULL COMMENT 'MOBILE_PHONE, OBD_TELEMATICS, DEDICATED_GPS, FUEL_SENSOR, COMBO_UNIT',
  install_status VARCHAR(50) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, INSTALLED, ACTIVE, SUSPENDED, DECOMMISSIONED',
  integration_provider VARCHAR(50) NOT NULL DEFAULT 'LDMS_MOBILE' COMMENT 'LDMS_MOBILE, GENERIC_MQTT, TRACCAR, GEOTAB, CALAMP, WIALON, CUSTOM_HTTP',
  device_label VARCHAR(150) NOT NULL,
  device_serial VARCHAR(100) NULL,
  external_device_id VARCHAR(150) NULL COMMENT 'Vendor hardware id',
  ingest_key VARCHAR(64) NOT NULL UNIQUE COMMENT 'API/MQTT auth key issued on install',
  tracks_gps TINYINT(1) NOT NULL DEFAULT 1,
  tracks_fuel TINYINT(1) NOT NULL DEFAULT 0,
  mqtt_topic VARCHAR(255) NULL COMMENT 'ldms/iot/{orgId}/{assetId}/gps when GENERIC_MQTT',
  installed_at DATETIME(6) NULL,
  last_telemetry_at DATETIME(6) NULL,
  notes VARCHAR(500) NULL,
  entity_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(6) NOT NULL,
  created_by VARCHAR(150) NOT NULL,
  modified_at DATETIME(6) NULL,
  modified_by VARCHAR(150) NULL,
  KEY idx_ftd_org (organization_id, entity_status),
  KEY idx_ftd_asset (fleet_asset_id, entity_status),
  KEY idx_ftd_ingest (ingest_key)
);
