-- ================================================================
-- Service: ldms-organization-management
-- Version: V1
-- Purpose: Greenfield baseline schema — organizations, industries,
--          branches, agents, relationships, and KYC review history.
-- ================================================================

CREATE TABLE industry (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    industry_code VARCHAR(50) NULL,
    description VARCHAR(500) NULL,
    regulatory_body_name VARCHAR(200) NULL,
    regulatory_body_contact_info VARCHAR(300) NULL,
    compliance_requirements VARCHAR(1000) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    entity_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(6) NOT NULL,
    created_by VARCHAR(150) NOT NULL,
    modified_at DATETIME(6) NULL,
    modified_by VARCHAR(150) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_industry_name (name),
    KEY idx_industry_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(300) NOT NULL,
    location_id BIGINT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NULL,
    organization_type VARCHAR(50) NULL,
    organization_classification VARCHAR(50) NOT NULL,
    industry_id BIGINT NULL,
    contact_person_first_name VARCHAR(100) NULL,
    contact_person_last_name VARCHAR(100) NULL,
    contact_person_email VARCHAR(255) NULL,
    contact_person_phone_number VARCHAR(50) NULL,
    contact_person_position VARCHAR(100) NULL,
    contact_person_gender VARCHAR(50) NULL,
    contact_person_national_id_number VARCHAR(100) NULL,
    contact_person_national_id_upload_id BIGINT NULL,
    contact_person_passport_number VARCHAR(100) NULL,
    contact_person_passport_upload_id BIGINT NULL,
    contact_person_date_of_birth VARCHAR(20) NULL,
    logo_upload_id BIGINT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_via_signup BOOLEAN NULL,
    registration_number VARCHAR(100) NULL,
    tax_number VARCHAR(100) NULL,
    registration_certificate_upload_id BIGINT NULL,
    tax_clearance_certificate_upload_id BIGINT NULL,
    business_license_upload_id BIGINT NULL,
    proof_of_address_upload_id BIGINT NULL,
    representative_national_id_number VARCHAR(100) NULL,
    representative_passport_number VARCHAR(100) NULL,
    industry_specific_license_upload_id BIGINT NULL,
    website_url VARCHAR(500) NULL,
    organization_description TEXT NULL,
    incorporation_date DATETIME(6) NULL,
    business_hours VARCHAR(200) NULL,
    number_of_employees INT NULL,
    annual_revenue_estimate DECIMAL(19,4) NULL,
    regions_served VARCHAR(500) NULL,
    subscription_plan_id BIGINT NULL,
    data_protection_officer_contact VARCHAR(255) NULL,
    two_factor_authentication_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    linked_in_url VARCHAR(500) NULL,
    facebook_url VARCHAR(500) NULL,
    twitter_url VARCHAR(500) NULL,
    instagram_url VARCHAR(500) NULL,
    youtube_url VARCHAR(500) NULL,
    latitude DECIMAL(10,6) NULL,
    longitude DECIMAL(11,6) NULL,
    assigned_account_manager_user_id BIGINT NULL,
    kyc_status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    submitted_at DATETIME(6) NULL,
    current_resubmission_cycle INT NOT NULL DEFAULT 0,
    stage1_reviewed_by VARCHAR(150) NULL,
    stage1_reviewed_at DATETIME(6) NULL,
    stage2_reviewed_by VARCHAR(150) NULL,
    stage2_reviewed_at DATETIME(6) NULL,
    last_rejection_reason VARCHAR(1000) NULL,
    resubmission_count INT NOT NULL DEFAULT 0,
    entity_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(6) NOT NULL,
    created_by VARCHAR(150) NOT NULL,
    modified_at DATETIME(6) NULL,
    modified_by VARCHAR(150) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_org_email (email),
    KEY idx_org_classification (organization_classification),
    KEY idx_org_kyc_status (kyc_status),
    KEY idx_org_is_verified (is_verified),
    KEY idx_org_entity_status (entity_status),
    KEY idx_org_classification_kyc (organization_classification, kyc_status),
    KEY idx_org_registration_number (registration_number),
    CONSTRAINT fk_org_industry FOREIGN KEY (industry_id) REFERENCES industry (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization_branch (
    id BIGINT NOT NULL AUTO_INCREMENT,
    organization_id BIGINT NOT NULL,
    branch_name VARCHAR(200) NOT NULL,
    branch_code VARCHAR(50) NULL,
    location_id BIGINT NULL,
    phone_number VARCHAR(50) NULL,
    email VARCHAR(255) NULL,
    latitude DECIMAL(10,6) NULL,
    longitude DECIMAL(11,6) NULL,
    is_head_office BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    manager_user_id BIGINT NULL,
    region VARCHAR(100) NULL,
    business_hours VARCHAR(200) NULL,
    entity_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(6) NOT NULL,
    created_by VARCHAR(150) NOT NULL,
    modified_at DATETIME(6) NULL,
    modified_by VARCHAR(150) NULL,
    PRIMARY KEY (id),
    KEY idx_branch_org (organization_id),
    KEY idx_branch_active (is_active),
    CONSTRAINT fk_branch_organization FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agent (
    id BIGINT NOT NULL AUTO_INCREMENT,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NULL,
    agent_kind VARCHAR(50) NOT NULL,
    agent_type VARCHAR(50) NULL,
    represented_organization_id BIGINT NULL,
    branch_id BIGINT NULL,
    first_name VARCHAR(100) NULL,
    last_name VARCHAR(100) NULL,
    email VARCHAR(255) NULL,
    phone_number VARCHAR(50) NULL,
    national_id_number VARCHAR(100) NULL,
    passport_number VARCHAR(100) NULL,
    date_of_birth VARCHAR(20) NULL,
    location_id BIGINT NULL,
    assigned_region VARCHAR(200) NULL,
    role VARCHAR(100) NULL,
    license_number VARCHAR(100) NULL,
    license_expiry_date DATE NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    entity_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(6) NOT NULL,
    created_by VARCHAR(150) NOT NULL,
    modified_at DATETIME(6) NULL,
    modified_by VARCHAR(150) NULL,
    PRIMARY KEY (id),
    KEY idx_agent_org (organization_id),
    KEY idx_agent_rep_org (represented_organization_id),
    KEY idx_agent_kind_type (agent_kind, agent_type),
    CONSTRAINT fk_agent_organization FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_agent_represented_org FOREIGN KEY (represented_organization_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_agent_branch FOREIGN KEY (branch_id) REFERENCES organization_branch (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agent_organization (
    id BIGINT NOT NULL AUTO_INCREMENT,
    agent_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    relationship_type VARCHAR(100) NOT NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    entity_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(6) NOT NULL,
    created_by VARCHAR(150) NOT NULL,
    modified_at DATETIME(6) NULL,
    modified_by VARCHAR(150) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_org_rel (agent_id, organization_id, relationship_type),
    CONSTRAINT fk_agent_org_agent FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_agent_org_organization FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization_customer_supplier (
    supplier_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    PRIMARY KEY (supplier_id, customer_id),
    KEY idx_ocs_customer (customer_id),
    CONSTRAINT fk_ocs_supplier FOREIGN KEY (supplier_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ocs_customer FOREIGN KEY (customer_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization_contracted_transporters (
    organization_id BIGINT NOT NULL,
    transporter_id BIGINT NOT NULL,
    PRIMARY KEY (organization_id, transporter_id),
    KEY idx_oct_transporter (transporter_id),
    CONSTRAINT fk_oct_organization FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_oct_transporter FOREIGN KEY (transporter_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization_kyc_review (
    id BIGINT NOT NULL AUTO_INCREMENT,
    organization_id BIGINT NOT NULL,
    stage VARCHAR(20) NOT NULL,
    decision VARCHAR(20) NOT NULL,
    reviewer_user_id BIGINT NULL,
    reviewer_username VARCHAR(150) NOT NULL,
    rejection_reason VARCHAR(1000) NULL,
    notes TEXT NULL,
    resubmission_cycle INT NOT NULL DEFAULT 0,
    reviewed_at DATETIME(6) NOT NULL,
    entity_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(6) NOT NULL,
    created_by VARCHAR(150) NOT NULL,
    modified_at DATETIME(6) NULL,
    modified_by VARCHAR(150) NULL,
    PRIMARY KEY (id),
    KEY idx_kyc_review_org (organization_id),
    KEY idx_kyc_review_org_cycle (organization_id, resubmission_cycle),
    KEY idx_kyc_review_stage_decision (stage, decision),
    CONSTRAINT fk_kyc_review_organization FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
