package projectlx.user.management.service.utils.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum I18Code {
    MESSAGE_CREATE_USER_INVALID_REQUEST("message.create.user.invalid.request"),
    MESSAGE_USER_ALREADY_EXISTS("message.user.already.exists"),
    MESSAGE_USER_CREATED_SUCCESSFULLY("message.user.created.successfully"),
    MESSAGE_USER_ID_SUPPLIED_INVALID("message.user.id.supplied.invalid"),
    MESSAGE_USER_NOT_FOUND("message.user.not.found"),
    MESSAGE_USER_RETRIEVED_SUCCESSFULLY("message.user.retrieved.successfully"),
    MESSAGE_UPDATE_USER_INVALID_REQUEST("message.update.user.invalid.request"),
    MESSAGE_USER_UPDATED_SUCCESSFULLY("message.user.updated.successfully"),
    MESSAGE_USER_DELETED_SUCCESSFULLY("message.user.deleted.successfully"),
    MESSAGE_USER_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.invalid.multiple.filters.request"),
    MESSAGE_USER_PASSWORD_INVALID("message.user.password.invalid"),
    MESSAGE_USER_PAGE_OUT_OF_BOUNDS("message.user.page.out.of.bounds"),
    MESSAGE_CREATE_USER_REQUEST_IS_NULL("message.create.user.request.is.null"),
    MESSAGE_CREATE_USER_REQUIRED_FIELDS_MISSING("message.create.user.required.fields.missing"),
    MESSAGE_CREATE_USER_NO_IDENTIFICATION_PROVIDED("message.create.user.no.identification.provided"),
    MESSAGE_CREATE_USER_INVALID_EMAIL_FORMAT("message.create.user.invalid.email.format"),
    MESSAGE_CREATE_USER_INVALID_USERNAME_FORMAT("message.create.user.invalid.username.format"),
    MESSAGE_CREATE_USER_INVALID_PHONE_NUMBER_FORMAT("message.create.user.invalid.phone.number.format"),
    MESSAGE_CREATE_USER_NAME_CONTAINS_DIGITS("message.create.user.name.contains.digits"),
    MESSAGE_CREATE_USER_INVALID_GENDER("message.create.user.invalid.gender"),
    MESSAGE_CREATE_USER_INVALID_DATE_OF_BIRTH("message.create.user.invalid.date.of.birth"),
    MESSAGE_CREATE_USER_INVALID_IMAGE_UPLOAD("message.create.user.invalid.image.upload"),
    MESSAGE_USER_ID_IS_NULL_OR_LESS_THAN_ONE("message.user.id.is.null.or.less.than.one"),
    MESSAGE_EDIT_USER_REQUEST_IS_NULL("message.edit.user.request.is.null"),
    MESSAGE_EDIT_USER_ID_LESS_THAN_ONE("message.edit.user.id.less.than.one"),
    MESSAGE_USERS_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.users.multiple.filters.request.is.null"),

    MESSAGE_USER_ACCOUNT_NOT_FOUND("message.user.account.not.found"),
    MESSAGE_USER_ACCOUNT_ALREADY_EXISTS("message.user.account.already.exists"),
    MESSAGE_CREATE_USER_ACCOUNT_INVALID_REQUEST("message.create.user.account.invalid.request"),
    MESSAGE_USER_ACCOUNT_CREATED_SUCCESSFULLY("message.user.account.created.successfully"),
    MESSAGE_USER_ACCOUNT_RETRIEVED_SUCCESSFULLY("message.user.account.retrieved.successfully"),
    MESSAGE_UPDATE_USER_ACCOUNT_INVALID_REQUEST("message.update.user.account.invalid.request"),
    MESSAGE_USER_ACCOUNT_UPDATED_SUCCESSFULLY("message.user.account.updated.successfully"),
    MESSAGE_USER_ACCOUNT_DELETED_SUCCESSFULLY("message.user.account.deleted.successfully"),
    MESSAGE_USER_ACCOUNT_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.account.invalid.multiple.filters.request"),

    // User Account Validator specific messages
    MESSAGE_CREATE_USER_ACCOUNT_REQUEST_IS_NULL("message.create.user.account.request.is.null"),
    MESSAGE_CREATE_USER_ACCOUNT_PHONE_NUMBER_MISSING("message.create.user.account.phone.number.missing"),
    MESSAGE_CREATE_USER_ACCOUNT_USER_ID_INVALID("message.create.user.account.user.id.invalid"),
    MESSAGE_CREATE_USER_ACCOUNT_PHONE_NUMBER_INVALID_FORMAT("message.create.user.account.phone.number.invalid.format"),
    MESSAGE_USER_ACCOUNT_ID_INVALID("message.user.account.id.invalid"),
    MESSAGE_UPDATE_USER_ACCOUNT_REQUEST_IS_NULL("message.update.user.account.request.is.null"),
    MESSAGE_USER_ACCOUNT_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.user.account.multiple.filters.request.is.null"),
    MESSAGE_USER_ACCOUNT_MULTIPLE_FILTERS_PAGE_LESS_THAN_ZERO("message.user.account.multiple.filters.page.less.than.zero"),
    MESSAGE_USER_ACCOUNT_STRING_INVALID("message.user.account.string.invalid"),
    MESSAGE_USER_ACCOUNT_LIST_INVALID("message.user.account.list.invalid"),
    MESSAGE_USER_ACCOUNT_LIST_CONTAINS_INVALID_ITEMS("message.user.account.list.contains.invalid.items"),
    MESSAGE_USER_ACCOUNT_PHONE_NUMBER_INVALID("message.user.account.phone.number.invalid"),
    MESSAGE_USER_ACCOUNT_NATIONAL_ID_INVALID("message.user.account.national.id.invalid"),
    MESSAGE_USER_ACCOUNT_USERNAME_INVALID("message.user.account.username.invalid"),
    MESSAGE_USER_ACCOUNT_PASSWORD_INVALID("message.user.account.password.invalid"),
    MESSAGE_USER_ACCOUNT_BOOLEAN_INVALID("message.user.account.boolean.invalid"),

    MESSAGE_USER_ADDRESS_NOT_FOUND("message.user.address.not.found"),
    MESSAGE_USER_ADDRESS_ALREADY_EXISTS("message.user.address.already.exists"),
    MESSAGE_CREATE_USER_ADDRESS_INVALID_REQUEST("message.create.user.address.invalid.request"),
    MESSAGE_ADDRESS_CREATED_SUCCESSFULLY("message.user.address.created.successfully"),
    MESSAGE_USER_ADDRESS_RETRIEVED_SUCCESSFULLY("message.user.address.retrieved.successfully"),
    MESSAGE_UPDATE_USER_ADDRESS_INVALID_REQUEST("message.update.user.address.invalid.request"),
    MESSAGE_USER_ADDRESS_UPDATED_SUCCESSFULLY("message.address.updated.successfully"),
    MESSAGE_USER_ADDRESS_DELETED_SUCCESSFULLY("message.user.address.deleted.successfully"),
    MESSAGE_USER_ADDRESS_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.address.invalid.multiple.filters.request"),
    MESSAGE_ADDRESS_CREATION_FAILED("message.address.creation.failed"),
    MESSAGE_LOCATION_SERVICE_ERROR("message.location.service.error"),
    MESSAGE_ADDRESS_ID_INVALID("message.address.id.invalid"),
    MESSAGE_ADDRESS_RETRIEVAL_FAILED("message.address.retrieval.failed"),
    MESSAGE_ADDRESS_UPDATE_FAILED("message.address.update.failed"),
    MESSAGE_ADDRESS_DELETION_FAILED("message.address.deletion.failed"),
    MESSAGE_LOCATION_SERVICE_UNAVAILABLE("message.location.service.unavailable"),

    MESSAGE_USER_GROUP_NOT_FOUND("message.user.group.not.found"),
    MESSAGE_USER_GROUP_ALREADY_EXISTS("message.user.group.already.exists"),
    MESSAGE_CREATE_USER_GROUP_INVALID_REQUEST("message.create.user.group.invalid.request"),
    MESSAGE_CREATE_USER_GROUP_REQUEST_IS_NULL("message.create.user.group.request.is.null"),
    MESSAGE_CREATE_USER_GROUP_NAME_MISSING("message.create.user.group.name.missing"),
    MESSAGE_CREATE_USER_GROUP_DESCRIPTION_MISSING("message.create.user.group.description.missing"),
    MESSAGE_CREATE_USER_GROUP_NAME_CONTAINS_DIGITS("message.create.user.group.name.contains.digits"),
    MESSAGE_USER_GROUP_CREATED_SUCCESSFULLY("message.user.group.created.successfully"),
    MESSAGE_USER_GROUP_RETRIEVED_SUCCESSFULLY("message.user.group.retrieved.successfully"),
    MESSAGE_UPDATE_USER_GROUP_INVALID_REQUEST("message.update.user.group.invalid.request"),
    MESSAGE_UPDATE_USER_GROUP_REQUEST_IS_NULL("message.update.user.group.request.is.null"),
    MESSAGE_UPDATE_USER_GROUP_NAME_MISSING("message.update.user.group.name.missing"),
    MESSAGE_UPDATE_USER_GROUP_DESCRIPTION_MISSING("message.update.user.group.description.missing"),
    MESSAGE_UPDATE_USER_GROUP_NAME_DOES_NOT_CONTAIN_DIGITS("message.update.user.group.name.does.not.contain.digits"),
    MESSAGE_USER_GROUP_UPDATED_SUCCESSFULLY("message.user.group.updated.successfully"),
    MESSAGE_USER_GROUP_DELETED_SUCCESSFULLY("message.user.group.deleted.successfully"),
    MESSAGE_USER_GROUP_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.group.invalid.multiple.filters.request"),
    MESSAGE_USER_GROUP_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.user.group.multiple.filters.request.is.null"),
    MESSAGE_USER_GROUP_MULTIPLE_FILTERS_PAGE_LESS_THAN_ZERO("message.user.group.multiple.filters.page.less.than.zero"),
    MESSAGE_INVALID_ASSIGN_USER_ROLE_TO_USER_GROUP_REQUEST("message.invalid.assign.user.role.to.user.group.request"),
    MESSAGE_ASSIGN_USER_ROLE_TO_USER_GROUP_REQUEST_IS_NULL("message.assign.user.role.to.user.group.request.is.null"),
    MESSAGE_ASSIGN_USER_ROLE_TO_USER_GROUP_USER_GROUP_ID_INVALID("message.assign.user.role.to.user.group.user.group.id.invalid"),
    MESSAGE_ASSIGN_USER_ROLE_TO_USER_GROUP_USER_ROLE_IDS_INVALID("message.assign.user.role.to.user.group.user.role.ids.invalid"),
    MESSAGE_ASSIGN_USER_ROLE_TO_USER_GROUP_USER_ROLE_ID_LESS_THAN_ONE("message.assign.user.role.to.user.group.user.role.id.less.than.one"),
    MESSAGE_INVALID_REMOVE_USER_ROLES_FROM_USER_GROUP_REQUEST("message.invalid.remove.user.roles.from.user.group.request"),
    MESSAGE_REMOVE_USER_ROLES_FROM_USER_GROUP_REQUEST_IS_NULL("message.remove.user.roles.from.user.group.request.is.null"),
    MESSAGE_REMOVE_USER_ROLES_FROM_USER_GROUP_USER_GROUP_ID_INVALID("message.remove.user.roles.from.user.group.user.group.id.invalid"),
    MESSAGE_REMOVE_USER_ROLES_FROM_USER_GROUP_USER_ROLE_IDS_INVALID("message.remove.user.roles.from.user.group.user.role.ids.invalid"),
    MESSAGE_REMOVE_USER_ROLES_FROM_USER_GROUP_USER_ROLE_ID_LESS_THAN_ONE("message.remove.user.roles.from.user.group.user.role.id.less.than.one"),
    MESSAGE_INVALID_ADD_USER_GROUP_TO_USER_REQUEST("message.invalid.add.user.group.to.user.request"),
    MESSAGE_ADD_USER_TO_USER_GROUP_REQUEST_IS_NULL("message.add.user.to.user.group.request.is.null"),
    MESSAGE_ADD_USER_TO_USER_GROUP_USER_GROUP_ID_INVALID("message.add.user.to.user.group.user.group.id.invalid"),
    MESSAGE_ADD_USER_TO_USER_GROUP_USER_ID_INVALID("message.add.user.to.user.group.user.id.invalid"),

    MESSAGE_USER_PASSWORD_NOT_FOUND("message.user.password.not.found"),
    MESSAGE_CREATE_USER_PASSWORD_INVALID_REQUEST("message.create.user.password.invalid.request"),
    MESSAGE_USER_PASSWORD_CREATED_SUCCESSFULLY("message.user.password.created.successfully"),
    MESSAGE_USER_PASSWORD_RETRIEVED_SUCCESSFULLY("message.user.password.retrieved.successfully"),
    MESSAGE_UPDATE_USER_PASSWORD_INVALID_REQUEST("message.update.user.password.invalid.request"),
    MESSAGE_USER_PASSWORD_UPDATED_SUCCESSFULLY("message.user.password.updated.successfully"),
    MESSAGE_DELETE_USER_PASSWORD_INVALID_REQUEST("message.delete.user.password.invalid.request"),
    MESSAGE_USER_PASSWORD_DELETED_SUCCESSFULLY("message.user.password.deleted.successfully"),
    MESSAGE_USER_PASSWORD_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.password.invalid.multiple.filters.request"),

    // User Password Validator specific messages
    MESSAGE_CREATE_USER_PASSWORD_REQUEST_IS_NULL("message.create.user.password.request.is.null"),
    MESSAGE_CREATE_USER_PASSWORD_PASSWORD_MISSING("message.create.user.password.password.missing"),
    MESSAGE_CREATE_USER_PASSWORD_USER_ID_INVALID("message.create.user.password.user.id.invalid"),
    MESSAGE_USER_PASSWORD_ID_INVALID("message.user.password.id.invalid"),
    MESSAGE_CHANGE_USER_PASSWORD_REQUEST_IS_NULL("message.change.user.password.request.is.null"),
    MESSAGE_USER_PASSWORD_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.user.password.multiple.filters.request.is.null"),
    MESSAGE_USER_PASSWORD_MULTIPLE_FILTERS_PAGE_LESS_THAN_ZERO("message.user.password.multiple.filters.page.less.than.zero"),
    MESSAGE_USER_PASSWORD_STRING_INVALID("message.user.password.string.invalid"),

    MESSAGE_USER_PREFERENCES_NOT_FOUND("message.user.preferences.not.found"),
    MESSAGE_CREATE_USER_PREFERENCES_INVALID_REQUEST("message.create.user.preferences.invalid.request"),
    MESSAGE_USER_PREFERENCES_ALREADY_EXISTS("message.user.preferences.already.exists"),
    MESSAGE_USER_PREFERENCES_CREATED_SUCCESSFULLY("message.user.preferences.created.successfully"),
    MESSAGE_USER_PREFERENCES_RETRIEVED_SUCCESSFULLY("message.user.preferences.retrieved.successfully"),
    MESSAGE_USER_PREFERENCES_UPDATED_SUCCESSFULLY("message.user.preferences.updated.successfully"),
    MESSAGE_USER_PREFERENCES_DELETED_SUCCESSFULLY("message.user.preferences.deleted.successfully"),
    MESSAGE_UPDATE_USER_PREFERENCES_INVALID_REQUEST("message.update.user.preferences.invalid.request"),
    MESSAGE_USER_PREFERENCES_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.preferences.invalid.multiple.filters.request"),
    MESSAGE_CREATE_USER_PREFERENCES_REQUEST_IS_NULL("message.create.user.preferences.request.is.null"),
    MESSAGE_CREATE_USER_PREFERENCES_PREFERRED_LANGUAGE_MISSING("message.create.user.preferences.preferred.language.missing"),
    MESSAGE_CREATE_USER_PREFERENCES_TIMEZONE_MISSING("message.create.user.preferences.timezone.missing"),
    MESSAGE_CREATE_USER_PREFERENCES_USER_ID_INVALID("message.create.user.preferences.user.id.invalid"),
    MESSAGE_CREATE_USER_PREFERENCES_TIMEZONE_INVALID("message.create.user.preferences.timezone.invalid"),
    MESSAGE_UPDATE_USER_PREFERENCES_REQUEST_IS_NULL("message.update.user.preferences.request.is.null"),
    MESSAGE_UPDATE_USER_PREFERENCES_ID_INVALID("message.update.user.preferences.id.invalid"),
    MESSAGE_UPDATE_USER_PREFERENCES_PREFERRED_LANGUAGE_MISSING("message.update.user.preferences.preferred.language.missing"),
    MESSAGE_UPDATE_USER_PREFERENCES_TIMEZONE_MISSING("message.update.user.preferences.timezone.missing"),
    MESSAGE_UPDATE_USER_PREFERENCES_USER_ID_INVALID("message.update.user.preferences.user.id.invalid"),
    MESSAGE_UPDATE_USER_PREFERENCES_TIMEZONE_INVALID("message.update.user.preferences.timezone.invalid"),
    MESSAGE_USER_PREFERENCES_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.user.preferences.multiple.filters.request.is.null"),
    MESSAGE_USER_PREFERENCES_MULTIPLE_FILTERS_PAGE_LESS_THAN_ZERO("message.user.preferences.multiple.filters.page.less.than.zero"),
    MESSAGE_USER_PREFERENCES_STRING_INVALID("message.user.preferences.string.invalid"),

    MESSAGE_USER_ROLE_NOT_FOUND("message.user.role.not.found"),
    MESSAGE_USER_ROLE_ALREADY_EXISTS("message.user.role.already.exists"),
    MESSAGE_CREATE_USER_ROLE_INVALID_REQUEST("message.create.user.role.invalid.request"),
    MESSAGE_USER_ROLE_CREATED_SUCCESSFULLY("message.user.role.created.successfully"),
    MESSAGE_USER_ROLE_RETRIEVED_SUCCESSFULLY("message.user.role.retrieved.successfully"),
    MESSAGE_UPDATE_USER_ROLE_INVALID_REQUEST("message.update.user.role.invalid.request"),
    MESSAGE_USER_ROLE_UPDATED_SUCCESSFULLY("message.user.role.updated.successfully"),
    MESSAGE_USER_ROLE_DELETED_SUCCESSFULLY("message.user.role.deleted.successfully"),
    MESSAGE_USER_ROLE_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.role.invalid.multiple.filters.request"),
    MESSAGE_USER_ROLES_ALREADY_ASSIGNED("message.user.roles.already.assigned"),
    MESSAGE_USER_ROLE_ASSIGNED_SUCCESSFULLY("message.user.role.assigned.successfully"),
    MESSAGE_USER_ROLE_NOT_ASSIGNED("message.user.role.not.assigned"),
    MESSAGE_USER_ROLES_REMOVED_SUCCESSFULLY("message.user.roles.removed.successfully"),

    MESSAGE_USER_SECURITY_NOT_FOUND("message.user.security.not.found"),
    MESSAGE_CREATE_USER_SECURITY_INVALID_REQUEST("message.create.user.security.invalid.request"),
    MESSAGE_USER_SECURITY_CREATED_SUCCESSFULLY("message.user.security.created.successfully"),
    MESSAGE_USER_SECURITY_RETRIEVED_SUCCESSFULLY("message.user.security.retrieved.successfully"),
    MESSAGE_USER_SECURITY_UPDATED_SUCCESSFULLY("message.user.security.updated.successfully"),
    MESSAGE_USER_SECURITY_DELETED_SUCCESSFULLY("message.user.security.deleted.successfully"),
    MESSAGE_USER_SECURITY_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.security.invalid.multiple.filters.request"),
    MESSAGE_UPDATE_USER_SECURITY_INVALID_REQUEST("message.update.user.security.invalid.request"),

    MESSAGE_USER_TYPE_NOT_FOUND("message.user.type.not.found"),
    MESSAGE_CREATE_USER_TYPE_INVALID_REQUEST("message.create.user.type.invalid.request"),
    MESSAGE_USER_TYPE_CREATED_SUCCESSFULLY("message.user.type.created.successfully"),
    MESSAGE_USER_TYPE_UPDATED_SUCCESSFULLY("message.user.type.updated.successfully"),
    MESSAGE_USER_TYPE_DELETED_SUCCESSFULLY("message.user.type.deleted.successfully"),
    MESSAGE_USER_TYPE_RETRIEVED_SUCCESSFULLY("message.user.type.retrieved.successfully"),
    MESSAGE_UPDATE_USER_TYPE_INVALID_REQUEST("message.update.user.type.invalid.request"),
    MESSAGE_USER_TYPE_INVALID_MULTIPLE_FILTERS_REQUEST("message.user.type.invalid.multiple.filters.request"),

    // User Type Validator specific messages
    MESSAGE_CREATE_USER_TYPE_REQUEST_IS_NULL("message.create.user.type.request.is.null"),
    MESSAGE_CREATE_USER_TYPE_NAME_MISSING("message.create.user.type.name.missing"),
    MESSAGE_CREATE_USER_TYPE_DESCRIPTION_MISSING("message.create.user.type.description.missing"),
    MESSAGE_USER_TYPE_ID_INVALID("message.user.type.id.invalid"),
    MESSAGE_UPDATE_USER_TYPE_REQUEST_IS_NULL("message.update.user.type.request.is.null"),
    MESSAGE_UPDATE_USER_TYPE_ID_INVALID("message.update.user.type.id.invalid"),
    MESSAGE_UPDATE_USER_TYPE_NAME_MISSING("message.update.user.type.name.missing"),
    MESSAGE_UPDATE_USER_TYPE_DESCRIPTION_MISSING("message.update.user.type.description.missing"),
    MESSAGE_USER_TYPE_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.user.type.multiple.filters.request.is.null"),
    MESSAGE_USER_TYPE_MULTIPLE_FILTERS_PAGE_LESS_THAN_ZERO("message.user.type.multiple.filters.page.less.than.zero"),
    MESSAGE_USER_TYPE_STRING_INVALID("message.user.type.string.invalid"),

    MESSAGE_INVALID_AUTHENTICATION_REQUEST("message.invalid.authentication.request"),
    MESSAGE_USER_AUTHENTICATED_SUCCESSFULLY("message.user.authenticated.successfully"),

    MESSAGE_REFRESH_TOKEN_REQUEST_INVALID("message.refresh.token.request.invalid"),
    MESSAGE_REFRESH_TOKEN_INVALID("message.refresh.token.invalid"),
    MESSAGE_REFRESH_TOKEN_REFRESHED_SUCCESSFULLY("message.refresh.token.refreshed.successfully"),

    MESSAGE_USERNAME_SUPPLIED_INVALID("message.username.supplied.invalid"),
    MESSAGE_PHONE_NUMBER_OR_EMAIL_SUPPLIED_INVALID("message.phone.number.or.email.supplied.invalid"),

    // User Role Validator specific messages
    MESSAGE_CREATE_USER_ROLE_REQUEST_IS_NULL("message.create.user.role.request.is.null"),
    MESSAGE_CREATE_USER_ROLE_NAME_MISSING("message.create.user.role.name.missing"),
    MESSAGE_CREATE_USER_ROLE_DESCRIPTION_MISSING("message.create.user.role.description.missing"),
    MESSAGE_CREATE_USER_ROLE_NAME_CONTAINS_DIGITS("message.create.user.role.name.contains.digits"),
    MESSAGE_UPDATE_USER_ROLE_REQUEST_IS_NULL("message.update.user.role.request.is.null"),
    MESSAGE_UPDATE_USER_ROLE_ID_INVALID("message.update.user.role.id.invalid"),
    MESSAGE_UPDATE_USER_ROLE_NAME_MISSING("message.update.user.role.name.missing"),
    MESSAGE_UPDATE_USER_ROLE_DESCRIPTION_MISSING("message.update.user.role.description.missing"),
    MESSAGE_UPDATE_USER_ROLE_NAME_CONTAINS_DIGITS("message.update.user.role.name.contains.digits"),
    MESSAGE_USER_ROLE_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.user.role.multiple.filters.request.is.null"),
    MESSAGE_USER_ROLE_MULTIPLE_FILTERS_PAGE_LESS_THAN_ZERO("message.user.role.multiple.filters.page.less.than.zero"),
    MESSAGE_USER_ROLE_STRING_INVALID("message.user.role.string.invalid"),

    // User Security Validator specific messages
    MESSAGE_CREATE_USER_SECURITY_REQUEST_IS_NULL("message.create.user.security.request.is.null"),
    MESSAGE_CREATE_USER_SECURITY_REQUIRED_FIELDS_MISSING("message.create.user.security.required.fields.missing"),
    MESSAGE_CREATE_USER_SECURITY_USER_ID_INVALID("message.create.user.security.user.id.invalid"),
    MESSAGE_UPDATE_USER_SECURITY_REQUEST_IS_NULL("message.update.user.security.request.is.null"),
    MESSAGE_UPDATE_USER_SECURITY_ID_INVALID("message.update.user.security.id.invalid"),
    MESSAGE_UPDATE_USER_SECURITY_REQUIRED_FIELDS_MISSING("message.update.user.security.required.fields.missing"),
    MESSAGE_UPDATE_USER_SECURITY_USER_ID_INVALID("message.update.user.security.user.id.invalid"),
    MESSAGE_USER_SECURITY_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.user.security.multiple.filters.request.is.null"),
    MESSAGE_USER_SECURITY_MULTIPLE_FILTERS_PAGE_LESS_THAN_ZERO("message.user.security.multiple.filters.page.less.than.zero"),
    MESSAGE_USER_SECURITY_STRING_INVALID("message.user.security.string.invalid"),
    MESSAGE_USER_SECURITY_BOOLEAN_INVALID("message.user.security.boolean.invalid"),

    // User Address Validator specific messages
    MESSAGE_CREATE_USER_ADDRESS_REQUEST_IS_NULL("message.create.user.address.request.is.null"),
    MESSAGE_CREATE_USER_ADDRESS_REQUIRED_FIELDS_MISSING("message.create.user.address.required.fields.missing"),
    MESSAGE_CREATE_USER_ADDRESS_COUNTRY_INVALID("message.create.user.address.country.invalid"),
    MESSAGE_USER_ADDRESS_ID_INVALID("message.user.address.id.invalid"),
    MESSAGE_EDIT_USER_ADDRESS_REQUEST_IS_NULL("message.edit.user.address.request.is.null"),
    MESSAGE_USER_ADDRESS_MULTIPLE_FILTERS_REQUEST_IS_NULL("message.user.address.multiple.filters.request.is.null"),
    MESSAGE_USER_ADDRESS_MULTIPLE_FILTERS_PAGE_LESS_THAN_ZERO("message.user.address.multiple.filters.page.less.than.zero"),
    MESSAGE_USER_ADDRESS_STRING_INVALID("message.user.address.string.invalid"),
    
    // Email verification messages
    MESSAGE_VERIFICATION_LINK_EXPIRED("message.verification.link.expired"),
    MESSAGE_VERIFICATION_LINK_INVALID("message.verification.link.invalid"),
    MESSAGE_EMAIL_VERIFIED_SUCCESSFULLY("message.email.verified.successfully"),
    MESSAGE_EMAIL_ALREADY_VERIFIED("message.email.already.verified"),
    MESSAGE_VERIFICATION_LINK_SENT_SUCCESSFULLY("message.verification.link.sent.successfully"),

    MESSAGE_FORGOT_PASSWORD_INVALID_REQUEST("message.forgot.password.invalid.request"),
    MESSAGE_FORGOT_PASSWORD_EMAIL_SENT("message.forgot.password.email.sent"),

    MESSAGE_RESET_TOKEN_INVALID("message.reset.token.invalid"),
    MESSAGE_RESET_TOKEN_EXPIRED("message.reset.token.expired"),
    MESSAGE_RESET_TOKEN_VALID("message.reset.token.valid"),

    MESSAGE_RESET_PASSWORD_INVALID_REQUEST("message.reset.password.invalid.request"),
    MESSAGE_PASSWORDS_DO_NOT_MATCH("message.passwords.do.not.match"),
    MESSAGE_PASSWORD_RESET_SUCCESSFUL("message.password.reset.successful"),
    MESSAGE_RESET_PASSWORD_REQUEST_IS_NULL("message.reset.password.request.is.null"),
    MESSAGE_RESET_TOKEN_MISSING("message.reset.token.missing"),
    MESSAGE_EMAIL_MISSING("message.email.missing"),
    MESSAGE_PASSWORD_MISSING("message.password.missing"),
    MESSAGE_CONFIRM_PASSWORD_MISSING("message.confirm.password.missing"),

    MESSAGE_EXPIRING_PASSWORDS_RETRIEVED_SUCCESSFULLY("message.user.password.expiring.retrieved.successfully"),
    MESSAGE_EXPIRING_PASSWORDS_RETRIEVE_FAILED("message.user.password.expiring.retrieve.failed");

    private final String code;
}
