server:
  port: 8099

spring:
  application:
    name: ldms-audit-trail
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${MYSQL_DATABASE:ldms_audit_trail}?useSSL=true&requireSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        prefetch: 20
        acknowledge-mode: manual
        default-requeue-rejected: false

ldms:
  audit:
    enabled: false

management:
  server:
    port: 9099
  tracing:
    sampling:
      probability: 0.05

logging:
  level:
    root: WARN
    projectlx: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
