server:
  port: 8087

spring:
  application:
    name: ldms-shipment-management
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/ldms_shipment_management?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    show-sql: false
clients:
  base-url:
    inventory-management: http://ldms-inventory-management
    documents-management: http://ldms-documents-management
    billing-payments: http://ldms-billing-payments

management:
  server:
    port: 9087
  tracing:
    sampling:
      probability: 0.05

logging:
  level:
    root: WARN
    projectlx: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}