server:
  port: 8092

spring:
  application:
    name: ldms-fuel-expenses
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/ldms_fuel_expenses?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    show-sql: false
clients:
  base-url:
    billing-payments: http://ldms-billing-payments
    trip-tracking: http://ldms-trip-tracking

management:
  server:
    port: 9092
  tracing:
    sampling:
      probability: 0.05

logging:
  level:
    root: WARN
    projectlx: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}