-- Invoices, payments, and driver expense reconciliation

CREATE TABLE invoice (
    id                          BIGINT          NOT NULL AUTO_INCREMENT,
    invoice_number              VARCHAR(50)     NOT NULL,
    organization_id             BIGINT          NOT NULL,
    supplier_id                 BIGINT          NULL,
    source_type                 VARCHAR(50)     NOT NULL,
    source_id                   BIGINT          NOT NULL,
    source_reference            VARCHAR(100)    NULL,
    grv_id                      BIGINT          NULL,
    grv_number                  VARCHAR(50)     NULL,
    purchase_order_id           BIGINT          NULL,
    purchase_order_number       VARCHAR(50)     NULL,
    transaction_currency_code   VARCHAR(3)      NOT NULL,
    base_currency_code          VARCHAR(3)      NOT NULL,
    exchange_rate_snapshot_id   BIGINT          NULL,
    subtotal_transaction        DECIMAL(19,4)   NOT NULL DEFAULT 0,
    subtotal_base               DECIMAL(19,4)   NOT NULL DEFAULT 0,
    tax_transaction             DECIMAL(19,4)   NOT NULL DEFAULT 0,
    tax_base                    DECIMAL(19,4)   NOT NULL DEFAULT 0,
    total_transaction           DECIMAL(19,4)   NOT NULL DEFAULT 0,
    total_base                  DECIMAL(19,4)   NOT NULL DEFAULT 0,
    payment_term                VARCHAR(50)     NULL,
    payment_due_date            DATE            NULL,
    status                      VARCHAR(50)     NOT NULL DEFAULT 'ISSUED',
    issued_at                   DATETIME(6)     NOT NULL,
    entity_status               VARCHAR(50)     NOT NULL DEFAULT 'ACTIVE',
    created_at                  DATETIME(6)     NOT NULL,
    created_by                  VARCHAR(255)    NOT NULL,
    modified_at                 DATETIME(6)     NULL,
    modified_by                 VARCHAR(255)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_invoice_number (invoice_number),
    KEY idx_invoice_org_status (organization_id, status),
    KEY idx_invoice_source (source_type, source_id),
    KEY idx_invoice_grv (grv_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE invoice_line (
    id                          BIGINT          NOT NULL AUTO_INCREMENT,
    invoice_id                  BIGINT          NOT NULL,
    line_number                 INT             NOT NULL,
    description                 VARCHAR(500)    NOT NULL,
    quantity                    DECIMAL(19,2)   NOT NULL DEFAULT 0,
    unit_price_transaction      DECIMAL(19,4)   NOT NULL DEFAULT 0,
    line_total_transaction      DECIMAL(19,4)   NOT NULL DEFAULT 0,
    unit_price_base             DECIMAL(19,4)   NOT NULL DEFAULT 0,
    line_total_base             DECIMAL(19,4)   NOT NULL DEFAULT 0,
    exchange_rate_snapshot_id   BIGINT          NULL,
    entity_status               VARCHAR(50)     NOT NULL DEFAULT 'ACTIVE',
    created_at                  DATETIME(6)     NOT NULL,
    created_by                  VARCHAR(255)    NOT NULL,
    modified_at                 DATETIME(6)     NULL,
    modified_by                 VARCHAR(255)    NULL,
    PRIMARY KEY (id),
    KEY idx_invoice_line_invoice (invoice_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payment (
    id                          BIGINT          NOT NULL AUTO_INCREMENT,
    payment_reference           VARCHAR(50)     NOT NULL,
    invoice_id                  BIGINT          NOT NULL,
    organization_id             BIGINT          NOT NULL,
    transaction_currency_code   VARCHAR(3)      NOT NULL,
    base_currency_code          VARCHAR(3)      NOT NULL,
    exchange_rate_snapshot_id   BIGINT          NULL,
    amount_transaction          DECIMAL(19,4)   NOT NULL,
    amount_base                 DECIMAL(19,4)   NOT NULL,
    payment_method              VARCHAR(50)     NULL,
    payment_date                DATE            NOT NULL,
    status                      VARCHAR(50)     NOT NULL DEFAULT 'COMPLETED',
    notes                       VARCHAR(500)    NULL,
    entity_status               VARCHAR(50)     NOT NULL DEFAULT 'ACTIVE',
    created_at                  DATETIME(6)     NOT NULL,
    created_by                  VARCHAR(255)    NOT NULL,
    modified_at                 DATETIME(6)     NULL,
    modified_by                 VARCHAR(255)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_payment_reference (payment_reference),
    KEY idx_payment_invoice (invoice_id),
    KEY idx_payment_org (organization_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE driver_expense_reconciliation (
    id                          BIGINT          NOT NULL AUTO_INCREMENT,
    expense_reference           VARCHAR(100)    NOT NULL,
    driver_id                   BIGINT          NOT NULL,
    organization_id             BIGINT          NOT NULL,
    trip_id                     BIGINT          NULL,
    transaction_currency_code   VARCHAR(3)      NOT NULL,
    base_currency_code          VARCHAR(3)      NOT NULL,
    exchange_rate_snapshot_id   BIGINT          NULL,
    amount_transaction          DECIMAL(19,4)   NOT NULL,
    amount_base                 DECIMAL(19,4)   NOT NULL,
    expense_category            VARCHAR(100)    NULL,
    expense_date                DATE            NOT NULL,
    status                      VARCHAR(50)     NOT NULL DEFAULT 'PENDING',
    approved_by                 VARCHAR(255)    NULL,
    approved_at                 DATETIME(6)     NULL,
    rejection_reason            VARCHAR(500)    NULL,
    entity_status               VARCHAR(50)     NOT NULL DEFAULT 'ACTIVE',
    created_at                  DATETIME(6)     NOT NULL,
    created_by                  VARCHAR(255)    NOT NULL,
    modified_at                 DATETIME(6)     NULL,
    modified_by                 VARCHAR(255)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_driver_expense_reference (expense_reference),
    KEY idx_driver_expense_org_status (organization_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
